import { Button,Card,Input,Textarea } from '@/components/ui/primitives';
import { useToast } from '@/components/ui/Toast';
import { supabase } from '@/lib/supabase';
import { BadgePercent,ExternalLink,Mail,Send,ShieldCheck,Sparkles } from 'lucide-react';
import { useMemo,useState } from 'react';

type CampaignType='sales'|'promotion';
const PRESETS={sales:{subject:'Simplify your daily collection reconciliation with HubVault',message:'Managing COD, cash, online collections and daily closing across your hub should not be complicated. HubVault brings your complete collection workflow into one clear dashboard.\n\nGet lifetime access and make every closing faster, accurate and accountable.',ctaLabel:'Explore HubVault',ctaUrl:'https://www.hubvault.in/buy-hubvault'},promotion:{subject:'Simplify Your Daily Collection Management with HubVault',message:'Managing COD collections, CMS deposits, cash handovers and reconciliation manually?\n\nHubVault helps Logistics, Courier, Warehouse and Last-Mile companies automate their daily collection process with complete accuracy.',ctaLabel:'Visit HubVault',ctaUrl:'https://www.hubvault.in'}};
const FEATURES=['💰 Cash Collection Tracking','🏦 CMS Deposit Management','🧾 Cash Denomination Calculator','📊 Smart Reports','📈 Dues & Advance Tracking','📤 Excel Export','🔐 Secure Cloud Backup','🌐 Multi Hub Support','📱 Mobile Friendly','⚡ Offline Support'];

function PromotionalPreview(){return <Card className="overflow-hidden bg-[#f4f7fb] p-3 sm:p-5"><div className="overflow-hidden rounded-2xl bg-white shadow-xl dark:bg-white"><div className="bg-[#0F172A] px-6 py-8 text-center"><img src="https://raw.githubusercontent.com/xpintus/hubvault/main/public/favicon.ico" alt="HubVault logo" className="mx-auto h-16 w-16"/><h2 className="mt-3 text-2xl font-black text-white">🚀 HubVault</h2><p className="mt-1 text-sm text-slate-300">Smart Collection Reconciliation Platform</p></div><div className="p-6 text-slate-700"><h3 className="text-xl font-black text-slate-900">💼 Simplify Your Daily Collection Management</h3><p className="mt-4 text-sm leading-7">Managing COD collections, CMS deposits, cash handovers and reconciliation manually?<br/><br/><b>HubVault</b> helps Logistics, Courier, Warehouse and Last-Mile companies automate their daily collection process with complete accuracy.</p><h3 className="mt-7 font-black text-slate-900">✨ Powerful Features</h3><div className="mt-3 grid grid-cols-2 gap-x-3 gap-y-2 text-xs">{FEATURES.map(feature=><span key={feature}>{feature}</span>)}</div><h3 className="mt-7 font-black text-slate-900">🎯 Why Choose HubVault?</h3><p className="mt-3 text-sm leading-7">✅ Save Hours Every Day<br/>✅ Reduce Manual Errors<br/>✅ Track Every Rupee<br/>✅ Real-Time Reports<br/>✅ Easy to Use Dashboard<br/>✅ Better Financial Control</p><div className="mt-7 text-center"><span className="inline-flex items-center gap-2 rounded-xl bg-[#2563EB] px-6 py-3 text-sm font-black text-white">🚀 Visit HubVault <ExternalLink className="h-4 w-4"/></span><p className="mt-3 text-xs text-slate-500">🌐 www.hubvault.in</p></div></div><div className="bg-slate-50 p-5 text-center text-xs text-slate-500"><p>Made for Logistics • Courier • Warehouse • E-commerce • Last Mile Operations</p><p className="mt-2 text-slate-400">© 2026 HubVault. All Rights Reserved.</p><p className="mt-2 text-[10px] text-slate-400">Unsubscribe from promotional emails</p></div></div></Card>}
function SalesPreview({subject,message,name,ctaLabel,ctaUrl}:{subject:string;message:string;name:string;ctaLabel:string;ctaUrl:string}){return <Card className="overflow-hidden"><div className="bg-gradient-to-br from-slate-950 to-indigo-600 p-6 text-white"><p className="text-lg font-black">HubVault</p><p className="mt-5 text-[10px] font-black tracking-[.16em] text-cyan-200">HUBVAULT FOR YOUR BUSINESS</p><h2 className="mt-2 text-2xl font-black leading-tight">{subject||'Your email subject'}</h2></div><div className="p-6"><p className="font-bold text-neutral-900 dark:text-white">Hi {name||'there'},</p><div className="mt-4 whitespace-pre-line text-sm leading-7 text-neutral-500">{message||'Your message preview will appear here.'}</div>{ctaLabel&&ctaUrl&&<span className="mt-5 inline-flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-3 text-sm font-black text-white">{ctaLabel}<ExternalLink className="h-4 w-4"/></span>}<div className="mt-7 border-t border-neutral-200 pt-4 text-xs text-neutral-400 dark:border-neutral-800">Includes HubVault branding and an unsubscribe link.</div></div></Card>}

export default function MailCampaigns(){
  const toast=useToast();const [type,setType]=useState<CampaignType>('sales');const [to,setTo]=useState('');const [recipientName,setRecipientName]=useState('');const [subject,setSubject]=useState(PRESETS.sales.subject);const [message,setMessage]=useState(PRESETS.sales.message);const [ctaLabel,setCtaLabel]=useState(PRESETS.sales.ctaLabel);const [ctaUrl,setCtaUrl]=useState(PRESETS.sales.ctaUrl);const [sending,setSending]=useState(false);
  const valid=useMemo(()=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(to.trim())&&subject.trim().length>=3&&message.trim().length>=10,[to,subject,message]);
  const chooseType=(next:CampaignType)=>{setType(next);setSubject(PRESETS[next].subject);setMessage(PRESETS[next].message);setCtaLabel(PRESETS[next].ctaLabel);setCtaUrl(PRESETS[next].ctaUrl);};
  const send=async()=>{if(!valid)return;setSending(true);try{let token=(await supabase.auth.getSession()).data.session?.access_token;if(!token)token=(await supabase.auth.refreshSession()).data.session?.access_token;if(!token)throw new Error('Session expired. Please log in again.');const response=await fetch('/api/send-campaign-email',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({to:to.trim(),recipientName:recipientName.trim(),subject:subject.trim(),message:message.trim(),ctaLabel:ctaLabel.trim(),ctaUrl:ctaUrl.trim(),campaignType:type})});const data=await response.json();if(!response.ok)throw new Error(data.message||'Email could not be sent');toast.success(`Email sent to ${to.trim()}`);setTo('');setRecipientName('');}catch(error){toast.error(error instanceof Error?error.message:'Email could not be sent');}finally{setSending(false);}};
  return <div className="mx-auto max-w-6xl space-y-6"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.16em] text-brand-600"><Sparkles className="h-4 w-4"/>Resend Campaigns</div><h1 className="mt-2 text-2xl font-black text-neutral-900 dark:text-white">Sales & promotional mail</h1><p className="mt-1 text-sm text-neutral-500">Send a polished, branded email to one customer at a time.</p></div><div className="grid gap-6 lg:grid-cols-[1fr_.82fr]"><Card className="p-5 sm:p-6"><div className="grid grid-cols-2 gap-3"><button onClick={()=>chooseType('sales')} className={`rounded-2xl border p-4 text-left ${type==='sales'?'border-brand-500 bg-brand-50 text-brand-700 dark:bg-brand-500/10 dark:text-brand-300':'border-neutral-200 dark:border-neutral-800'}`}><Mail className="h-5 w-5"/><p className="mt-2 text-sm font-black">Sales email</p></button><button onClick={()=>chooseType('promotion')} className={`rounded-2xl border p-4 text-left ${type==='promotion'?'border-violet-500 bg-violet-50 text-violet-700 dark:bg-violet-500/10 dark:text-violet-300':'border-neutral-200 dark:border-neutral-800'}`}><BadgePercent className="h-5 w-5"/><p className="mt-2 text-sm font-black">Promotional</p></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input label="Recipient email *" type="email" value={to} onChange={event=>setTo(event.target.value)} placeholder="customer@example.com"/><Input label="Recipient name" value={recipientName} onChange={event=>setRecipientName(event.target.value)} placeholder="Customer name"/></div><div className="mt-4"><Input label="Email subject *" value={subject} maxLength={150} onChange={event=>setSubject(event.target.value)}/></div><div className="mt-4"><Textarea label="Message *" value={message} rows={9} maxLength={5000} onChange={event=>setMessage(event.target.value)}/></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Input label="Button text" value={ctaLabel} onChange={event=>setCtaLabel(event.target.value)}/><Input label="Button link (HTTPS)" value={ctaUrl} onChange={event=>setCtaUrl(event.target.value)}/></div><Button onClick={send} loading={sending} disabled={!valid} icon={<Send className="h-4 w-4"/>} className="mt-6 w-full">Send email via Resend</Button><p className="mt-3 flex items-center justify-center gap-2 text-xs text-neutral-500"><ShieldCheck className="h-4 w-4"/>Only Super Admins are authorized by the server.</p></Card>{type==='promotion'?<PromotionalPreview/>:<SalesPreview subject={subject} message={message} name={recipientName} ctaLabel={ctaLabel} ctaUrl={ctaUrl}/>}</div></div>;
}
