import { Camera,Download,FileSpreadsheet,History,Layers3,PackagePlus,QrCode,Save,Share2,Trash2,Upload } from 'lucide-react';
import { useEffect,useState } from 'react';

export type CashCounts=Record<number,number>;
export type CashSnapshot={id:string;name:string;date:string;expected:string;counts:CashCounts;total:number;createdAt:string};
export type CashBranding={company:string;branch:string;cashier:string;logo?:string};
type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>};
const NOTE_VALUES=[500,200,100,50,20,10,5,2,1] as const;

const HISTORY_KEY='hubvault.cash.history.v1';
const PRESET_KEY='hubvault.cash.presets.v1';
const BAG_KEY='hubvault.cash.bags.v1';
const BRAND_KEY='hubvault.cash.branding.v1';
const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)??'') as T;}catch{return fallback;}};
const write=(key:string,value:unknown)=>localStorage.setItem(key,JSON.stringify(value));
const money=(value:number)=>`₹${value.toLocaleString('en-IN')}`;

export function CashCalculatorTools({snapshot,onRestore,onApplyCounts,onBrandingChange}:{snapshot:CashSnapshot;onRestore:(snapshot:CashSnapshot)=>void;onApplyCounts:(counts:CashCounts)=>void;onBrandingChange:(branding:CashBranding)=>void}){
  const [history,setHistory]=useState<CashSnapshot[]>(()=>read(HISTORY_KEY,[]));
  const [presets,setPresets]=useState<Array<{id:string;name:string;counts:CashCounts}>>(()=>read(PRESET_KEY,[]));
  const [bags,setBags]=useState<Array<{id:string;name:string;counts:CashCounts;total:number}>>(()=>read(BAG_KEY,[]));
  const [branding,setBranding]=useState<CashBranding>(()=>read(BRAND_KEY,{company:'HubVault',branch:'',cashier:''}));
  const [qr,setQr]=useState('');
  const [message,setMessage]=useState('');
  const [installPrompt,setInstallPrompt]=useState<InstallPromptEvent|null>(null);
  const [cameraPreview,setCameraPreview]=useState('');
  const [cameraBusy,setCameraBusy]=useState(false);
  const [cameraProgress,setCameraProgress]=useState(0);
  const [cameraSuggestions,setCameraSuggestions]=useState<CashCounts>({});
  const [cameraText,setCameraText]=useState('');

  useEffect(()=>{const handler=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPromptEvent);};window.addEventListener('beforeinstallprompt',handler);return()=>window.removeEventListener('beforeinstallprompt',handler);},[]);
  useEffect(()=>onBrandingChange(branding),[branding,onBrandingChange]);
  const persistHistory=(next:CashSnapshot[])=>{setHistory(next);write(HISTORY_KEY,next);};
  const saveHistory=()=>{const next=[{...snapshot,id:crypto.randomUUID(),createdAt:new Date().toISOString()},...history].slice(0,20);persistHistory(next);setMessage('Calculation saved to recent history.');};
  const savePreset=()=>{const name=window.prompt('Preset name');if(!name?.trim())return;const next=[...presets,{id:crypto.randomUUID(),name:name.trim(),counts:snapshot.counts}];setPresets(next);write(PRESET_KEY,next);};
  const addBag=()=>{const name=window.prompt('Bag / counter name',`Bag ${bags.length+1}`);if(!name?.trim())return;const next=[...bags,{id:crypto.randomUUID(),name:name.trim(),counts:snapshot.counts,total:snapshot.total}];setBags(next);write(BAG_KEY,next);};
  const bundle=(note:number)=>onApplyCounts({...snapshot.counts,[note]:(snapshot.counts[note]??0)+100});
  const payload=()=>({v:1,name:snapshot.name,date:snapshot.date,expected:snapshot.expected,counts:snapshot.counts});
  const shareLink=()=>{const encoded=btoa(unescape(encodeURIComponent(JSON.stringify(payload()))));return `${location.origin}${location.pathname}#/tools/cash-calculator?cash=${encodeURIComponent(encoded)}`;};
  const generateQr=async()=>{const QRCode=await import('qrcode');setQr(await QRCode.toDataURL(shareLink(),{width:320,margin:2,color:{dark:'#17152f',light:'#ffffff'}}));};
  const copyLink=async()=>{await navigator.clipboard.writeText(shareLink());setMessage('Shareable calculation link copied.');};
  const exportExcel=async()=>{const XLSX=await import('xlsx');const rows=Object.entries(snapshot.counts).filter(([,qty])=>qty>0).map(([note,qty])=>({Denomination:Number(note),Quantity:qty,Amount:Number(note)*qty}));const ws=XLSX.utils.json_to_sheet(rows);XLSX.utils.sheet_add_aoa(ws,[[branding.company||'HubVault',branding.branch||'',branding.cashier||''],['Name',snapshot.name],['Date',snapshot.date],['Expected',snapshot.expected||''],['Total',snapshot.total]],{origin:'E1'});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Cash Count');XLSX.writeFile(wb,`cash-count-${snapshot.date}.xlsx`);};
  const uploadLogo=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{const next={...branding,logo:String(reader.result)};setBranding(next);write(BRAND_KEY,next);};reader.readAsDataURL(file);};
  const updateBrand=(patch:Partial<CashBranding>)=>{const next={...branding,...patch};setBranding(next);write(BRAND_KEY,next);};
  const cameraEstimate=async(file?:File)=>{if(!file)return;setCameraBusy(true);setCameraProgress(0);setCameraSuggestions({});setCameraText('');if(cameraPreview.startsWith('blob:'))URL.revokeObjectURL(cameraPreview);setCameraPreview(URL.createObjectURL(file));setMessage('Loading on-device OCR. The first scan can take a little longer.');try{const Tesseract=await import('tesseract.js');const result=await Tesseract.recognize(file,'eng',{logger:event=>{if(event.status==='recognizing text')setCameraProgress(Math.round((event.progress??0)*100));}});const text=result.data.text.replace(/,/g,'');setCameraText(text.trim());const lines=text.split(/\r?\n/).map(line=>line.trim()).filter(Boolean);const estimated:CashCounts={};NOTE_VALUES.forEach(note=>{const pattern=`(?:₹|rs\\.?|inr)?\\s*${note}(?!\\d)`;const lineMatches=lines.filter(line=>new RegExp(pattern,'i').test(line));const allMatches=text.match(new RegExp(pattern,'gi'))?.length??0;const quantity=Math.max(lineMatches.length,allMatches);if(quantity>0)estimated[note]=quantity;});setCameraSuggestions(estimated);setMessage(Object.keys(estimated).length?'OCR scan complete. Check and edit every suggested quantity before applying.':'No denomination was detected clearly. Try a brighter, straight photo or enter quantities manually.');}catch(error){console.error('Cash photo OCR failed',error);setMessage('Photo scan failed. Check your internet for the first OCR download, then retry with a clear, well-lit photo.');}finally{setCameraBusy(false);}};
  const applyCameraEstimate=()=>{onApplyCounts({...snapshot.counts,...cameraSuggestions});setMessage('Verified camera suggestions applied. Please physically confirm the final total.');};
  const install=async()=>{if(!installPrompt){setMessage('Use your browser menu and choose “Add to Home screen”.');return;}await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null);};

  return <section className="mt-5 rounded-3xl border border-slate-200 bg-white/80 p-3 shadow-xl dark:border-white/10 dark:bg-slate-900/70 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-brand-600">Smart tools</p><h2 className="text-xl font-black dark:text-white">Save, organize & share</h2></div><button onClick={saveHistory} disabled={snapshot.total===0} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-brand-600 px-4 text-xs font-black text-white disabled:opacity-40"><Save className="h-4 w-4"/>Save calculation</button></div>{message&&<p className="mt-3 rounded-xl bg-brand-50 p-3 text-xs font-semibold text-brand-700 dark:bg-brand-500/10 dark:text-brand-300">{message}</p>}
    <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">
      <Tool title="Bundles & presets" icon={<PackagePlus className="h-4 w-4"/>}><p className="text-xs text-slate-500">Add sealed 100-note bundles instantly.</p><div className="mt-2 flex flex-wrap gap-2">{[500,200,100,50,20,10].map(note=><button key={note} onClick={()=>bundle(note)} className="rounded-lg bg-slate-100 px-2.5 py-2 text-xs font-bold dark:bg-white/10">₹{note} × 100</button>)}</div><button onClick={savePreset} disabled={snapshot.total===0} className="mt-3 text-xs font-black text-brand-600 disabled:opacity-40">+ Save current preset</button>{presets.map(p=><div key={p.id} className="mt-2 flex items-center gap-2"><button onClick={()=>onApplyCounts(p.counts)} className="min-w-0 flex-1 truncate rounded-lg border p-2 text-left text-xs font-bold dark:border-white/10">{p.name}</button><button onClick={()=>{const next=presets.filter(x=>x.id!==p.id);setPresets(next);write(PRESET_KEY,next);}} aria-label={`Delete ${p.name}`}><Trash2 className="h-4 w-4 text-red-500"/></button></div>)}</Tool>
      <Tool title="Multi-bag counting" icon={<Layers3 className="h-4 w-4"/>}><button onClick={addBag} disabled={snapshot.total===0} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-black text-white disabled:opacity-40 dark:bg-cyan-300 dark:text-slate-950">Save current as bag</button>{bags.map(b=><div key={b.id} className="mt-2 flex items-center gap-2 rounded-xl bg-slate-50 p-2 text-xs dark:bg-white/5"><button onClick={()=>onApplyCounts(b.counts)} className="min-w-0 flex-1 text-left"><b>{b.name}</b><span className="ml-2 text-slate-500">{money(b.total)}</span></button><button onClick={()=>{const next=bags.filter(x=>x.id!==b.id);setBags(next);write(BAG_KEY,next);}}><Trash2 className="h-4 w-4 text-red-500"/></button></div>)}<p className="mt-3 text-sm font-black">Grand total: {money(bags.reduce((sum,b)=>sum+b.total,0))}</p></Tool>
      <Tool title="Share & export" icon={<Share2 className="h-4 w-4"/>}><div className="grid grid-cols-2 gap-2"><button onClick={copyLink} className="rounded-xl bg-slate-100 p-2 text-xs font-bold dark:bg-white/10"><Share2 className="mx-auto mb-1 h-4 w-4"/>Copy link</button><button onClick={generateQr} className="rounded-xl bg-slate-100 p-2 text-xs font-bold dark:bg-white/10"><QrCode className="mx-auto mb-1 h-4 w-4"/>QR code</button><button onClick={exportExcel} disabled={snapshot.total===0} className="rounded-xl bg-slate-100 p-2 text-xs font-bold disabled:opacity-40 dark:bg-white/10"><FileSpreadsheet className="mx-auto mb-1 h-4 w-4"/>Excel</button><button onClick={install} className="rounded-xl bg-slate-100 p-2 text-xs font-bold dark:bg-white/10"><Download className="mx-auto mb-1 h-4 w-4"/>Install app</button></div>{qr&&<img src={qr} alt="Calculation QR code" className="mx-auto mt-3 w-40 rounded-xl bg-white p-2"/>}</Tool>
      <Tool title="Custom branding" icon={<Upload className="h-4 w-4"/>}><div className="grid gap-2"><input value={branding.company} onChange={e=>updateBrand({company:e.target.value})} placeholder="Company name" className="rounded-xl border bg-transparent p-2 text-xs dark:border-white/10"/><input value={branding.branch} onChange={e=>updateBrand({branch:e.target.value})} placeholder="Branch" className="rounded-xl border bg-transparent p-2 text-xs dark:border-white/10"/><input value={branding.cashier} onChange={e=>updateBrand({cashier:e.target.value})} placeholder="Cashier" className="rounded-xl border bg-transparent p-2 text-xs dark:border-white/10"/><label className="cursor-pointer rounded-xl border border-dashed p-2 text-center text-xs dark:border-white/20">Upload logo<input type="file" accept="image/*" onChange={e=>uploadLogo(e.target.files?.[0])} className="hidden"/></label></div></Tool>
      <Tool title="Camera estimate" icon={<Camera className="h-4 w-4"/>}><p className="text-xs text-amber-600 dark:text-amber-300">Estimate only—not counterfeit detection or a verified note counter. Use a clear, straight photo and physically verify every quantity.</p><label className={`mt-3 flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-slate-100 p-3 text-xs font-black dark:bg-white/10 ${cameraBusy?'pointer-events-none opacity-60':''}`}><Camera className="h-4 w-4"/>{cameraBusy?`Scanning… ${cameraProgress}%`:'Take / upload photo'}<input type="file" accept="image/*" capture="environment" disabled={cameraBusy} onChange={e=>cameraEstimate(e.target.files?.[0])} className="hidden"/></label>{cameraBusy&&<div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200 dark:bg-white/10"><div className="h-full rounded-full bg-brand-600 transition-all" style={{width:`${Math.max(4,cameraProgress)}%`}}/></div>}{cameraPreview&&<img src={cameraPreview} alt="Cash selected for OCR" className="mt-3 max-h-44 w-full rounded-xl bg-black/5 object-contain"/>}{Object.keys(cameraSuggestions).length>0&&<div className="mt-3"><p className="text-xs font-black">Detected quantity suggestions</p><div className="mt-2 grid grid-cols-3 gap-2">{NOTE_VALUES.filter(note=>cameraSuggestions[note]>0).map(note=><label key={note} className="rounded-xl bg-slate-50 p-2 text-[10px] font-bold dark:bg-white/5">₹{note}<input aria-label={`Detected ₹${note} quantity`} type="number" inputMode="numeric" min={0} value={cameraSuggestions[note]??0} onChange={event=>setCameraSuggestions(current=>({...current,[note]:Math.max(0,Math.floor(Number(event.target.value)||0))}))} className="mt-1 w-full rounded-lg border bg-transparent p-1.5 text-center text-sm font-black dark:border-white/10"/></label>)}</div><button onClick={applyCameraEstimate} className="mt-3 w-full rounded-xl bg-brand-600 p-2.5 text-xs font-black text-white">Apply verified estimate</button></div>}{cameraText&&<details className="mt-3 rounded-xl bg-slate-50 p-2 text-[10px] dark:bg-white/5"><summary className="cursor-pointer font-bold">View recognized text</summary><pre className="mt-2 max-h-28 overflow-auto whitespace-pre-wrap text-slate-500">{cameraText}</pre></details>}</Tool>
      <Tool title="Recent history" icon={<History className="h-4 w-4"/>}>{history.length===0?<p className="text-xs text-slate-500">No saved calculations yet.</p>:history.slice(0,20).map(item=><div key={item.id} className="mt-2 flex items-center gap-2 rounded-xl bg-slate-50 p-2 text-xs dark:bg-white/5"><button onClick={()=>onRestore(item)} className="min-w-0 flex-1 text-left"><b className="block truncate">{item.name||item.date}</b><span>{money(item.total)}</span></button><button onClick={()=>persistHistory(history.filter(x=>x.id!==item.id))}><Trash2 className="h-4 w-4 text-red-500"/></button></div>)}</Tool>
    </div>
  </section>;
}

function Tool({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <details className="group rounded-2xl border border-slate-200 p-3 dark:border-white/10" open><summary className="flex cursor-pointer list-none items-center gap-2 text-sm font-black dark:text-white">{icon}{title}</summary><div className="mt-3">{children}</div></details>;}
