import { EmployeeDRSMetrics, OverallDRSSummary } from '@/types/drs';

export async function exportDRSPerformancePDF(
  summary: OverallDRSSummary,
  employeeMetrics: EmployeeDRSMetrics[],
  fileNamePrefix: string = 'DRS_Performance_Executive_Report'
): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF();

  // Title & Header
  doc.setFontSize(18);
  doc.setTextColor(79, 70, 229); // Brand Indigo
  doc.text('HUBVAULT DRS PERFORMANCE EXECUTIVE REPORT', 14, 20);

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`File: ${summary.fileName} | Date: ${summary.reportDate || new Date().toLocaleDateString()} | Generated: ${new Date().toLocaleString()}`, 14, 27);

  doc.setLineWidth(0.5);
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 31, 196, 31);

  // Section 1: Key Performance Indicators Summary Grid
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('1. Executive Logistics KPI Summary', 14, 40);

  let y = 48;
  const kpis = [
    ['Total OFD (Unique AWBs)', String(summary.totalOfd), 'Overall Delivery Rate', `${summary.overallDeliveryPct}%`],
    ['Total Delivered', String(summary.totalDelivered), '1st Attempt Delivery Rate', `${summary.firstAttemptDeliveryPct}%`],
    ['Total UNDEL', String(summary.totalUndel), 'Reattempt Delivery Rate', `${summary.reattemptDeliveryPct}%`],
    ['1st Attempt OFD / DEL', `${summary.firstAttemptOfd} / ${summary.firstAttemptDelivered}`, '1st Attempt Contribution', `${summary.firstAttemptContributionPct}%`],
    ['Reattempt OFD / DEL', `${summary.reattemptOfd} / ${summary.reattemptDelivered}`, 'Reattempt Contribution', `${summary.reattemptContributionPct}%`],
    ['Total RTO / Cancelled', `${summary.totalRto} / ${summary.totalCancelled}`, 'Total COD Value', `Rs ${summary.totalCodValue.toLocaleString()}`],
  ];

  doc.setFontSize(9);
  kpis.forEach(([label1, val1, label2, val2]) => {
    doc.setTextColor(100, 116, 139);
    doc.text(label1, 14, y);
    doc.setTextColor(15, 23, 42);
    doc.text(val1, 70, y);

    doc.setTextColor(100, 116, 139);
    doc.text(label2, 110, y);
    doc.setTextColor(15, 23, 42);
    doc.text(val2, 170, y);

    y += 6;
  });

  y += 6;
  doc.line(14, y, 196, y);
  y += 8;

  // Section 2: Top 10 Delivery Executive Performance Leaderboard
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('2. Executive Performance Leaderboard (Top 10)', 14, y);
  y += 8;

  // Table Headers
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Rank', 14, y);
  doc.text('Executive Name', 28, y);
  doc.text('Total OFD', 80, y);
  doc.text('1st DEL', 105, y);
  doc.text('Re DEL', 125, y);
  doc.text('Total DEL', 145, y);
  doc.text('Overall %', 170, y);

  y += 4;
  doc.setDrawColor(203, 213, 225);
  doc.line(14, y, 196, y);
  y += 5;

  const top10 = employeeMetrics.slice(0, 10);
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);

  top10.forEach((e, idx) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(`#${idx + 1}`, 14, y);
    doc.text(String(e.employee_name).slice(0, 25), 28, y);
    doc.text(String(e.total_ofd), 80, y);
    doc.text(String(e.first_attempt_delivered), 105, y);
    doc.text(String(e.reattempt_delivered), 125, y);
    doc.text(String(e.total_delivered), 145, y);
    doc.text(`${e.overall_delivery_pct}%`, 170, y);
    y += 6;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by HubVault Enterprise Logistics BI Analytics System', 14, 285);

  const dateStr = new Date().toISOString().split('T')[0];
  doc.save(`${fileNamePrefix}_${dateStr}.pdf`);
}
