import SEO from '@/components/SEO';
import { ArrowRight,CheckCircle2,Infinity as InfinityIcon,ShieldCheck,Sparkles,WalletCards } from 'lucide-react';

const PAGE_URL='https://www.hubvault.in/buy-hubvault';
const CHECKOUT_URL='/#/buy-now';
const DESCRIPTION='Explore HubVault pricing and buy a ₹999 lifetime license for collection reconciliation, COD tracking, daily closing, dues, recovery and multi-hub reports.';
const FEATURES=['COD cash and online collection reconciliation','Collector-wise daily closing and approval','Employee dues and recovery history','CMS deposit and handover records','Multi-hub dashboards and user controls','Excel, PDF and operational reports'];
const STRUCTURED_DATA=[
  {'@context':'https://schema.org','@type':'Product','@id':`${PAGE_URL}#product`,name:'HubVault Lifetime License',brand:{'@type':'Brand',name:'HubVault'},url:PAGE_URL,image:'https://www.hubvault.in/og-image-v2.jpg',description:DESCRIPTION,category:'Collection reconciliation software',offers:{'@type':'Offer',url:'https://www.hubvault.in/#/buy-now',price:'999',priceCurrency:'INR',availability:'https://schema.org/InStock'},additionalProperty:FEATURES.map(item=>({'@type':'PropertyValue',name:'Included feature',value:item}))},
  {'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:'https://www.hubvault.in/'},{'@type':'ListItem',position:2,name:'Buy HubVault',item:PAGE_URL}]},
];

export default function BuyHubVault(){return <>
  <SEO title="Buy HubVault – ₹999 Lifetime License | Official Pricing" description={DESCRIPTION} path="/buy-hubvault" image="https://www.hubvault.in/og-image-v2.jpg" type="product" structuredData={STRUCTURED_DATA}/>
  <main className="bg-slate-50 text-slate-900 dark:bg-[#080b16] dark:text-white">
    <section className="relative isolate overflow-hidden border-b border-slate-200 px-4 py-16 dark:border-white/10 sm:px-6 sm:py-24"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_20%_10%,rgba(124,58,237,.22),transparent_36%),radial-gradient(circle_at_85%_20%,rgba(34,211,238,.16),transparent_32%)]"/><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="inline-flex items-center gap-2 rounded-full bg-violet-100 px-3 py-1.5 text-xs font-black uppercase tracking-wider text-violet-700 dark:bg-violet-500/15 dark:text-violet-200"><Sparkles className="h-4 w-4"/>Official HubVault pricing</p><h1 className="mt-5 text-4xl font-black leading-tight tracking-tight sm:text-5xl">Buy HubVault with a <span className="text-violet-600 dark:text-cyan-300">₹999 lifetime license</span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">One-time access to HubVault’s collection reconciliation suite for logistics and delivery operations. No recurring subscription fee.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={CHECKOUT_URL} className="inline-flex min-h-13 items-center justify-center gap-2 rounded-2xl bg-violet-600 px-7 py-3.5 text-sm font-black text-white shadow-xl shadow-violet-600/25 hover:bg-violet-700">Continue to secure purchase <ArrowRight className="h-4 w-4"/></a><a href="/collection-reconciliation-software" className="inline-flex min-h-13 items-center justify-center rounded-2xl border border-slate-300 px-7 py-3.5 text-sm font-black dark:border-white/15">Explore the product</a></div><p className="mt-4 text-xs text-slate-500">This information page opens the existing HubVault Buy Now checkout when you continue.</p></div><div className="rounded-[2rem] bg-[#111327] p-6 text-white shadow-2xl sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Lifetime plan</p><div className="mt-3 flex items-end gap-2"><strong className="text-5xl font-black">₹999</strong><span className="pb-1 text-white/50">one time</span></div><div className="mt-7 grid gap-3">{FEATURES.map(item=><div key={item} className="flex gap-3 rounded-2xl bg-white/[.06] p-3 text-sm font-bold"><CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-300"/>{item}</div>)}</div></div></div></section>
    <section className="px-4 py-16 sm:px-6"><div className="mx-auto max-w-6xl"><h2 className="text-center text-3xl font-black">What your HubVault license includes</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{[[InfinityIcon,'Lifetime access','Use the purchased HubVault license without a monthly or yearly subscription fee.'],[WalletCards,'Collection operations','Bring COD cash, online payments, deposits, dues and recovery into one workflow.'],[ShieldCheck,'Official purchase flow','Continue from this page to the existing HubVault account creation and payment checkout.']].map(([Icon,title,text])=>{const FeatureIcon=Icon as typeof InfinityIcon;return <article key={String(title)} className="rounded-3xl border border-slate-200 bg-white p-6 dark:border-white/10 dark:bg-white/[.04]"><FeatureIcon className="h-7 w-7 text-violet-600 dark:text-cyan-300"/><h3 className="mt-4 text-lg font-black">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{String(text)}</p></article>})}</div></div></section>
  </main>
</>}
