import SEO from '@/components/SEO';
import { CashBranding,CashCalculatorTools,CashCounts,CashSnapshot } from '@/components/cash-calculator/CashCalculatorTools';
import { ThemeToggle } from '@/components/ui/ThemeToggle';
import { Banknote,CalendarDays,Check,ChevronDown,ChevronUp,Clipboard,FileDown,Mic,MicOff,Minus,Printer,Redo2,RotateCcw,Share2,Sparkles,Target,Undo2,UserRound,Volume2,VolumeX } from 'lucide-react';
import { KeyboardEvent,useCallback,useEffect,useMemo,useRef,useState } from 'react';

const NOTES = [500,200,100,50,20,10,5,2,1] as const;
type NoteValue = typeof NOTES[number];
type ReceiptStatus = 'matched' | 'shortage' | 'excess';
type SpeechRecognitionLike = { lang:string;interimResults:boolean;continuous:boolean;start:()=>void;stop:()=>void;onresult:((event:{results:ArrayLike<{0:{transcript:string}}>} )=>void)|null;onerror:((event:{error:string})=>void)|null;onend:(()=>void)|null };
type SpeechRecognitionConstructor = new()=>SpeechRecognitionLike;

const localDate = () => {
  const date = new Date();
  return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
};
const emptyCounts = () => Object.fromEntries(NOTES.map(note => [note,0])) as Record<NoteValue,number>;
const DRAFT_KEY='hubvault.cash.draft.v1';
const CASH_CALCULATOR_URL='https://www.hubvault.in/tools/cash-calculator';
const CASH_CALCULATOR_TITLE='Smart Cash Calculator with AI Voice & Photo Count | HubVault';
const CASH_CALCULATOR_DESCRIPTION='Free smart cash calculator for Indian currency with AI-assisted voice entry, photo OCR estimates, cash reconciliation, multi-bag totals, PDF, Excel and QR sharing.';
const CASH_CALCULATOR_FAQS=[
  {question:'Is the HubVault cash denomination calculator free?',answer:'Yes. The calculator is free to use for counting Indian currency notes, checking totals and reconciling expected cash.'},
  {question:'Which Indian currency denominations are supported?',answer:'It supports ₹500, ₹200, ₹100, ₹50, ₹20, ₹10, ₹5, ₹2 and ₹1 denominations.'},
  {question:'Does HubVault upload my cash calculation?',answer:'No. Calculator drafts and recent history are stored locally on your device unless you choose to create and share a calculation link.'},
  {question:'Can I use it for COD and logistics cash reconciliation?',answer:'Yes. Enter the expected COD cash and counted denominations to see the exact shortage, excess or matched status.'},
  {question:'What makes this a smart cash calculator?',answer:'Along with instant denomination totals, HubVault offers Hindi and English voice-assisted entry, spoken totals, editable photo OCR suggestions, undo and redo, saved presets, 100-note bundles, multi-bag counting and automatic shortage or excess calculation.'},
  {question:'Can the calculator estimate notes from a photo?',answer:'Yes. The browser-based OCR tool can suggest denomination quantities from a clear cash photo. It is an editable estimate, not a verified note counter or counterfeit detector, so every quantity must be physically checked before use.'},
  {question:'Can I export or share a cash count?',answer:'Yes. You can copy a WhatsApp-ready summary, share a calculation link or QR code, download a branded PDF or Excel file, and print receipts for 2-inch and 3-inch thermal printers.'},
];
const CASH_CALCULATOR_STRUCTURED_DATA=[
  {'@context':'https://schema.org','@type':'WebApplication','@id':`${CASH_CALCULATOR_URL}#app`,name:'HubVault Smart Cash Calculator',alternateName:['AI-assisted Cash Calculator','Indian Cash Denomination Calculator','Cash Tally Calculator'],url:CASH_CALCULATOR_URL,applicationCategory:'FinanceApplication',applicationSubCategory:'Cash denomination counter and reconciliation tool',operatingSystem:'Any',browserRequirements:'Requires a modern web browser with JavaScript enabled',inLanguage:['en-IN','hi-IN'],description:CASH_CALCULATOR_DESCRIPTION,image:'https://www.hubvault.in/og-image-v2.jpg',isAccessibleForFree:true,offers:{'@type':'Offer',price:'0',priceCurrency:'INR'},featureList:['Instant Indian currency denomination counting for ₹500, ₹200, ₹100, ₹50, ₹20, ₹10, ₹5, ₹2 and ₹1','AI-assisted Hindi and English voice entry for up to nine denominations','Spoken live cash total with speed and volume controls','Editable photo OCR denomination estimates with physical-verification warning','Expected versus collected COD cash reconciliation','Automatic matched, shortage and excess calculation','100-note cash bundles and reusable denomination presets','Multi-bag cash counting with grand total','Undo, redo and recoverable reset','WhatsApp-ready cash summary and device sharing','Shareable calculation link and QR code','Branded PDF and Excel export','2-inch and 3-inch thermal receipt printing','Local draft and recent calculation history','Installable progressive web app']},
  {'@context':'https://schema.org','@type':'WebPage','@id':`${CASH_CALCULATOR_URL}#webpage`,url:CASH_CALCULATOR_URL,name:CASH_CALCULATOR_TITLE,description:CASH_CALCULATOR_DESCRIPTION,inLanguage:'en-IN',isPartOf:{'@type':'WebSite',name:'HubVault',url:'https://www.hubvault.in/'},mainEntity:{'@id':`${CASH_CALCULATOR_URL}#app`},breadcrumb:{'@id':`${CASH_CALCULATOR_URL}#breadcrumb`}},
  {'@context':'https://schema.org','@type':'BreadcrumbList','@id':`${CASH_CALCULATOR_URL}#breadcrumb`,itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:'https://www.hubvault.in/'},{'@type':'ListItem',position:2,name:'Tools',item:'https://www.hubvault.in/tools'},{'@type':'ListItem',position:3,name:'Smart Cash Calculator',item:CASH_CALCULATOR_URL}]},
  {'@context':'https://schema.org','@type':'FAQPage',mainEntity:CASH_CALCULATOR_FAQS.map(item=>({'@type':'Question',name:item.question,acceptedAnswer:{'@type':'Answer',text:item.answer}}))},
];
const readDraft=()=>{if(typeof localStorage==='undefined')return null;try{return JSON.parse(localStorage.getItem(DRAFT_KEY)??'null') as {name:string;date:string;expected:string;counts:Record<NoteValue,number>}|null;}catch{return null;}};
const money = (value: number) => `₹${Math.abs(value).toLocaleString('en-IN')}`;
const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[char] ?? char);
const SMALL_WORDS=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'];
const TENS_WORDS=['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'];
const numberWords=(value:number):string=>{const n=Math.floor(Math.abs(value));if(n<20)return SMALL_WORDS[n];if(n<100)return `${TENS_WORDS[Math.floor(n/10)]}${n%10?` ${SMALL_WORDS[n%10]}`:''}`;if(n<1000)return `${SMALL_WORDS[Math.floor(n/100)]} hundred${n%100?` ${numberWords(n%100)}`:''}`;if(n<100000)return `${numberWords(Math.floor(n/1000))} thousand${n%1000?` ${numberWords(n%1000)}`:''}`;if(n<10000000)return `${numberWords(Math.floor(n/100000))} lakh${n%100000?` ${numberWords(n%100000)}`:''}`;return n.toLocaleString('en-IN');};
const QUANTITY_WORDS:Record<string,number>={...Object.fromEntries([...SMALL_WORDS.map((word,index)=>[word,index]),...TENS_WORDS.map((word,index)=>[word,index*10]).filter(([word])=>word)]),'एक':1,'दो':2,'तीन':3,'चार':4,'पांच':5,'पाँच':5,'छह':6,'सात':7,'आठ':8,'नौ':9,'दस':10,'ग्यारह':11,'बारह':12,'तेरह':13,'चौदह':14,'पंद्रह':15,'सोलह':16,'सत्रह':17,'अठारह':18,'उन्नीस':19,'बीस':20,'तीस':30,'चालीस':40,'पचास':50,'साठ':60,'सत्तर':70,'अस्सी':80,'नब्बे':90,ek:1,do:2,teen:3,char:4,panch:5,paanch:5,chhah:6,saat:7,aath:8,nau:9,das:10,bees:20,tees:30,chalis:40,pachas:50,pachaas:50};
const NOTE_ALIASES:[NoteValue,RegExp][]=[[500,/(?:\bfive hundred\b|\b500\b|पांच सौ|पाँच सौ|\bpaa?nch sau\b)/],[200,/(?:\btwo hundred\b|\b200\b|दो सौ|\bdo sau\b)/],[100,/(?:\bone hundred\b|\bhundred\b|\b100\b|एक सौ|सौ|\bek sau\b)/],[50,/(?:\bfifty\b|\b50\b|पचास|\bpachaa?s\b)/],[20,/(?:\btwenty\b|\b20\b|बीस|\bbees\b)/],[10,/(?:\bten\b|\b10\b|दस|\bdas\b)/],[5,/(?:\bfive\b|\b5\b|पांच|पाँच|\bpaa?nch\b)/],[2,/(?:\btwo\b|\b2\b|दो|\bdo\b)/],[1,/(?:\bone\b|\b1\b|एक|\bek\b)/]];
const parseQuantity=(value:string)=>{const cleaned=value.replace(/(?:rupees?|notes?|quantity|set|add|for|of|ke|to|and|रुपये?|नोट|के|तो|और|लगाओ|डालो|जोड़ो)/g,' ').trim();const numeric=cleaned.match(/\d+/);if(numeric)return Math.max(0,Number(numeric[0]));let quantity=0;for(const part of cleaned.split(' ').filter(Boolean)){if(part==='hundred'||part==='सौ'||part==='sau')quantity*=100;else quantity+=QUANTITY_WORDS[part]??0;}return quantity;};
export const isVoiceTotalRequest=(transcript:string)=>/(?:what(?:'s| is)? (?:the )?total|tell (?:me )?(?:the )?total|live total|total batao|कुल|टोटल|कितना (?:हुआ|है))/.test(transcript.toLowerCase());
export const parseVoiceCashCommands=(transcript:string):Array<{note:NoteValue;quantity:number}>=>{const text=transcript.toLowerCase().replace(/-/g,' ').replace(/\s+/g,' ').trim();return text.split(/(?:notes?|नोट)[,;]?\s*/).map(segment=>{const candidates=NOTE_ALIASES.map(([note,pattern])=>{const match=segment.match(pattern);return match?.index===undefined?null:{note,start:match.index,end:match.index+match[0].length};}).filter((item):item is {note:NoteValue;start:number;end:number}=>item!==null).sort((a,b)=>a.start-b.start||b.end-a.end);const denomination=candidates[0];if(!denomination)return null;const quantity=parseQuantity(segment.slice(denomination.end));return quantity>0?{note:denomination.note,quantity}:null;}).filter((command):command is {note:NoteValue;quantity:number}=>command!==null);};
export const parseVoiceCashCommand=(transcript:string):{note:NoteValue;quantity:number}|null=>parseVoiceCashCommands(transcript)[0]??null;
export const mergeVoiceCashCommands=(current:Record<NoteValue,number>,commands:Array<{note:NoteValue;quantity:number}>):Record<NoteValue,number>=>{const next={...current};commands.forEach(command=>{next[command.note]=command.quantity;});return next;};
export const buildDenominationAnnouncement=(note:NoteValue,quantity:number,total:number,increased:boolean,language:'en-IN'|'hi-IN')=>language==='hi-IN'?(increased?`आपके ${note} रुपये के ${quantity} नोट ऐड हुए हैं और टोटल ${total.toLocaleString('hi-IN')} रुपये हुए हैं`:`${note} रुपये के नोट अब ${quantity} हैं और टोटल ${total.toLocaleString('hi-IN')} रुपये है`):(increased?`${quantity} notes of ${note} rupees have been added. The total is ${numberWords(total)} rupees`:`The ${note} rupee note count is now ${quantity}. The total is ${numberWords(total)} rupees`);

export const calculateCashTotal = (counts: Partial<Record<NoteValue,number>>) => NOTES.reduce((sum,note) => sum+(counts[note]??0)*note,0);
export const reconcileCash = (expected: number,collected: number): { variance:number;status:ReceiptStatus } => {
  const variance=collected-expected;
  return { variance,status:variance===0?'matched':variance<0?'shortage':'excess' };
};
export const buildCashSummary = ({ name,date,hasExpected,expected,collected,totalNotes,counts }:{ name:string;date:string;hasExpected:boolean;expected:number;collected:number;totalNotes:number;counts:Partial<Record<NoteValue,number>> }) => {
  const denominationLines=NOTES.filter(note=>(counts[note]??0)>0).map(note=>`₹${note} x ${counts[note]} = ${money(note*(counts[note]??0))}`);
  const reconciliation=reconcileCash(expected,collected);
  return [
    '*HubVault Cash Summary*',...(name.trim()?[`Name: ${name.trim()}`]:[]),`Date: ${date}`,'',...denominationLines,'',
    `Total Notes: ${totalNotes}`,`Total Cash: ${money(collected)}`,
    ...(hasExpected?[`Expected: ${money(expected)}`,`Collected: ${money(collected)}`,`Variance: ${reconciliation.variance<0?'-':reconciliation.variance>0?'+':''}${money(reconciliation.variance)}`,`Status: ${reconciliation.status.toUpperCase()}`]:[]),
    '','Generated with HubVault Cash Calculator',
  ].join('\n');
};

export default function CashCalculator() {
  const initialDraft=useMemo(readDraft,[]);
  const [name,setName]=useState(initialDraft?.name??'');
  const [date,setDate]=useState(initialDraft?.date??localDate);
  const [expected,setExpected]=useState(initialDraft?.expected??'');
  const [counts,setCounts]=useState<Record<NoteValue,number>>(()=>({...emptyCounts(),...initialDraft?.counts}));
  const [copied,setCopied]=useState(false);
  const [listening,setListening]=useState(false);
  const [voiceLanguage,setVoiceLanguage]=useState<'en-IN'|'hi-IN'>('en-IN');
  const [voiceMessage,setVoiceMessage]=useState('Speak up to 9 denominations in one go');
  const [heroCollapsed,setHeroCollapsed]=useState(false);
  const [soundEnabled,setSoundEnabled]=useState(true);
  const [voiceSpeed,setVoiceSpeed]=useState(.88);
  const [voiceVolume,setVoiceVolume]=useState(.75);
  const [continuousVoice,setContinuousVoice]=useState(false);
  const [transcript,setTranscript]=useState('');
  const [pastCounts,setPastCounts]=useState<Array<Record<NoteValue,number>>>([]);
  const [futureCounts,setFutureCounts]=useState<Array<Record<NoteValue,number>>>([]);
  const [resetBackup,setResetBackup]=useState<{name:string;date:string;expected:string;counts:Record<NoteValue,number>}|null>(null);
  const [branding,setBranding]=useState<CashBranding>({company:'HubVault',branch:'',cashier:''});
  const recognitionRef=useRef<SpeechRecognitionLike|null>(null);
  const manualVoiceStopRef=useRef(false);
  const currentCountsRef=useRef<Record<NoteValue,number>>({...counts});
  const previousCountsRef=useRef<Record<NoteValue,number>>(emptyCounts());
  const totalNotes=useMemo(()=>NOTES.reduce((sum,note)=>sum+counts[note],0),[counts]);
  const collected=useMemo(()=>calculateCashTotal(counts),[counts]);
  const expectedAmount=Math.max(0,Number(expected)||0);
  const hasExpected=expected.trim()!=='';
  const reconciliation=reconcileCash(expectedAmount,collected);

  const applyCounts=useCallback((next:CashCounts)=>{const previous={...currentCountsRef.current};const normalized={...emptyCounts(),...next};currentCountsRef.current=normalized;setPastCounts(history=>[...history,previous].slice(-30));setFutureCounts([]);setCounts(normalized);if('vibrate'in navigator)navigator.vibrate(18);},[]);
  const setCount=(note:NoteValue,value:string)=>applyCounts({...counts,[note]:Math.max(0,Math.floor(Number(value)||0))});
  const adjust=(note:NoteValue,delta:number)=>applyCounts({...counts,[note]:Math.max(0,counts[note]+delta)});
  const undo=()=>{const previous=pastCounts[pastCounts.length-1];if(!previous)return;setFutureCounts(next=>[{...counts},...next].slice(0,30));setCounts(previous);setPastCounts(items=>items.slice(0,-1));};
  const redo=()=>{const next=futureCounts[0];if(!next)return;setPastCounts(items=>[...items,{...counts}].slice(-30));setCounts(next);setFutureCounts(items=>items.slice(1));};
  const announceTotal=useCallback((amount=collected)=>{if(!soundEnabled||amount<=0||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const text=voiceLanguage==='hi-IN'?`अभी तक कुल ${amount.toLocaleString('hi-IN')} रुपये हुए हैं`:`Live total is ${numberWords(amount)} rupees`;const utterance=new SpeechSynthesisUtterance(text);utterance.lang=voiceLanguage;utterance.rate=voiceSpeed;utterance.volume=voiceVolume;window.speechSynthesis.speak(utterance);setVoiceMessage(voiceLanguage==='hi-IN'?`कुल राशि: ${money(amount)}`:`Live total: ${money(amount)}`);},[collected,soundEnabled,voiceLanguage,voiceSpeed,voiceVolume]);
  const announceDenomination=useCallback((note:NoteValue,quantity:number,total:number,increased:boolean)=>{if(!soundEnabled||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(buildDenominationAnnouncement(note,quantity,total,increased,voiceLanguage));utterance.lang=voiceLanguage;utterance.rate=voiceSpeed;utterance.volume=voiceVolume;window.speechSynthesis.speak(utterance);setVoiceMessage(voiceLanguage==='hi-IN'?`${note} के ${quantity} नोट • कुल ${money(total)}`:`${quantity} × ${money(note)} • Total ${money(total)}`);},[soundEnabled,voiceLanguage,voiceSpeed,voiceVolume]);
  const focusNext=(event:KeyboardEvent<HTMLInputElement>,index:number)=>{
    if(event.key==='Enter')(document.querySelector(`[data-note-index="${index+1}"]`) as HTMLInputElement|null)?.focus();
  };

  const applySpokenInput=(value:string)=>{const normalized=value.toLowerCase();setTranscript(value);if(/(?:^|\s)(?:done|stop|बस|रुको)(?:\s|$)/.test(normalized)){manualVoiceStopRef.current=true;recognitionRef.current?.stop();setVoiceMessage('Voice session stopped.');return;}if(/(?:reset all|सब reset|सब रीसेट)/.test(normalized)){const current={...currentCountsRef.current};setResetBackup({name,date,expected,counts:current});const empty=emptyCounts();currentCountsRef.current=empty;setCounts(empty);setVoiceMessage('All denominations reset.');return;}const remove=normalized.match(/(500|200|100|50|20|10|5|2|1)\s*(?:वाले?|रुपये?)?\s*(?:हटाओ|remove)/);if(remove){applyCounts({...currentCountsRef.current,[Number(remove[1])]:0});return;}const correction=normalized.match(/(500|200|100|50|20|10|5|2|1).*?(?:नहीं|not).*?(\d+)/);if(correction){applyCounts({...currentCountsRef.current,[Number(correction[1])]:Number(correction[2])});return;}if(isVoiceTotalRequest(value)){announceTotal(calculateCashTotal(currentCountsRef.current));return;}const commands=parseVoiceCashCommands(value);if(commands.length===0){setVoiceMessage(voiceLanguage==='hi-IN'?`समझ नहीं आया: “${value}”`:`Could not understand: “${value}”`);return;}applyCounts(mergeVoiceCashCommands(currentCountsRef.current,commands));setVoiceMessage(voiceLanguage==='hi-IN'?`${commands.length} मूल्य एक साथ जोड़े गए`:`${commands.length} denominations added together`);};
  const toggleVoice=()=>{if(listening){manualVoiceStopRef.current=true;recognitionRef.current?.stop();return;}const speechWindow=window as typeof window&{SpeechRecognition?:SpeechRecognitionConstructor;webkitSpeechRecognition?:SpeechRecognitionConstructor};const Recognition=speechWindow.SpeechRecognition??speechWindow.webkitSpeechRecognition;if(!Recognition){setVoiceMessage(voiceLanguage==='hi-IN'?'यह ब्राउज़र वॉइस कमांड सपोर्ट नहीं करता।':'Voice commands are not supported in this browser.');return;}const recognition=new Recognition();manualVoiceStopRef.current=false;recognition.lang=voiceLanguage;recognition.interimResults=false;recognition.continuous=continuousVoice;recognition.onresult=event=>{const value=event.results[event.results.length-1]?.[0]?.transcript??'';applySpokenInput(value);};recognition.onerror=event=>setVoiceMessage(event.error==='not-allowed'?(voiceLanguage==='hi-IN'?'माइक्रोफ़ोन की अनुमति नहीं मिली।':'Microphone permission was denied.'):(voiceLanguage==='hi-IN'?'आवाज़ सुनाई नहीं दी।':'Voice command could not be captured.'));recognition.onend=()=>{if(continuousVoice&&!manualVoiceStopRef.current){window.setTimeout(()=>{try{recognition.start();}catch{/* browser is still ending */}},250);return;}setListening(false);};recognitionRef.current=recognition;setListening(true);setVoiceMessage(voiceLanguage==='hi-IN'?'सुन रहा हूँ…':'Listening…');recognition.start();};
  useEffect(()=>()=>recognitionRef.current?.stop(),[]);
  useEffect(()=>{currentCountsRef.current={...counts};},[counts]);
  useEffect(()=>{if(heroCollapsed||!window.matchMedia('(max-width: 639px)').matches)return;const timer=window.setTimeout(()=>setHeroCollapsed(true),1000);return()=>window.clearTimeout(timer);},[heroCollapsed]);
  useEffect(()=>{const previous=previousCountsRef.current;const changedNote=NOTES.find(note=>previous[note]!==counts[note]);previousCountsRef.current={...counts};if(!changedNote)return;const quantity=counts[changedNote];const increased=quantity>previous[changedNote];const timer=window.setTimeout(()=>announceDenomination(changedNote,quantity,collected,increased),1000);return()=>window.clearTimeout(timer);},[counts,collected,announceDenomination]);
  useEffect(()=>{localStorage.setItem(DRAFT_KEY,JSON.stringify({name,date,expected,counts}));},[name,date,expected,counts]);
  useEffect(()=>{const encoded=new URLSearchParams(location.search||(location.hash.split('?')[1]??'')).get('cash');if(!encoded)return;try{const shared=JSON.parse(decodeURIComponent(escape(atob(encoded)))) as {name?:string;date?:string;expected?:string;counts?:CashCounts};if(shared.name!==undefined)setName(shared.name);if(shared.date)setDate(shared.date);if(shared.expected!==undefined)setExpected(shared.expected);if(shared.counts)setCounts({...emptyCounts(),...shared.counts});setVoiceMessage('Shared calculation restored.');}catch{setVoiceMessage('This shared calculation link is invalid.');}},[]);
  useEffect(()=>{if(!resetBackup)return;const timer=window.setTimeout(()=>setResetBackup(null),6000);return()=>window.clearTimeout(timer);},[resetBackup]);

  const summaryText=()=>buildCashSummary({name,date,hasExpected,expected:expectedAmount,collected,totalNotes,counts});

  const copyWhatsApp=async()=>{
    await navigator.clipboard.writeText(summaryText()); setCopied(true); window.setTimeout(()=>setCopied(false),1800);
  };
  const shareReceipt=async()=>{
    if(navigator.share) await navigator.share({title:'HubVault Cash Summary',text:summaryText()}); else await copyWhatsApp();
  };

  const downloadPdf=async()=>{
    const { jsPDF }=await import('jspdf');
    const doc=new jsPDF({unit:'mm',format:'a4'});
    doc.setFillColor(79,70,229); doc.roundedRect(14,12,182,28,4,4,'F');
    doc.setFillColor(255,255,255); doc.roundedRect(20,18,16,16,3,3,'F');
    if(branding.logo){try{doc.addImage(branding.logo,'PNG',20,18,16,16);}catch{doc.setTextColor(79,70,229);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('HV',24,28);}}else{doc.setTextColor(79,70,229);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('HV',24,28);}
    doc.setTextColor(255,255,255); doc.setFontSize(19); doc.text(branding.company||'HubVault',42,25); doc.setFontSize(9); doc.text(`${branding.branch?`${branding.branch} - `:''}Cash Count Summary`,42,32);
    doc.setTextColor(30,41,59); doc.setFontSize(10); doc.setFont('helvetica','normal');
    doc.text(`Date: ${date}`,145,49); if(name.trim())doc.text(`Name: ${name.trim()}`,14,49);if(branding.cashier)doc.text(`Cashier: ${branding.cashier}`,14,56);
    let y=68; doc.setFillColor(241,245,249); doc.rect(14,y-7,182,9,'F'); doc.setFont('helvetica','bold');
    doc.text('Denomination',18,y-1); doc.text('Quantity',91,y-1); doc.text('Amount',162,y-1); y+=8;
    doc.setFont('helvetica','normal');
    NOTES.filter(note=>counts[note]>0).forEach(note=>{doc.text(`Rs. ${note}`,18,y);doc.text(String(counts[note]),96,y);doc.text(`Rs. ${(note*counts[note]).toLocaleString('en-IN')}`,162,y);doc.line(14,y+2,196,y+2);y+=8;});
    y+=4; doc.setFillColor(248,250,252); doc.roundedRect(14,y,182,38,3,3,'F'); doc.setFont('helvetica','bold');doc.setFontSize(11);
    doc.text(`Total Notes: ${totalNotes}`,20,y+10);doc.text(`Total Cash: Rs. ${collected.toLocaleString('en-IN')}`,20,y+19);
    if(hasExpected){doc.text(`Expected: Rs. ${expectedAmount.toLocaleString('en-IN')}`,108,y+10);doc.text(`Variance: ${reconciliation.variance<0?'-':reconciliation.variance>0?'+':''}Rs. ${Math.abs(reconciliation.variance).toLocaleString('en-IN')}`,108,y+19);const statusColor:Record<ReceiptStatus,[number,number,number]>={matched:[22,163,74],shortage:[220,38,38],excess:[217,119,6]};doc.setTextColor(...statusColor[reconciliation.status]);doc.text(`Status: ${reconciliation.status.toUpperCase()}`,108,y+28);}
    doc.setTextColor(100,116,139);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text('Generated with HubVault Cash Calculator - hubvault.in',14,287);
    doc.save(`HubVault-Cash-Summary-${date}.pdf`);
  };

  const printThermal=(width:58|80)=>{
    const popup=window.open('','_blank',`width=${width===58?300:420},height=700`); if(!popup)return;
    const rows=NOTES.filter(note=>counts[note]>0).map(note=>`<tr><td>Rs.${note} x ${counts[note]}</td><td>Rs.${(note*counts[note]).toLocaleString('en-IN')}</td></tr>`).join('');
    const nameLine=name.trim()?`<div>Name: ${escapeHtml(name.trim())}</div>`:'';const reconciliationRows=hasExpected?`<tr><td>Expected</td><td>Rs.${expectedAmount.toLocaleString('en-IN')}</td></tr><tr><td>Variance</td><td>${reconciliation.variance<0?'-':reconciliation.variance>0?'+':''}Rs.${Math.abs(reconciliation.variance).toLocaleString('en-IN')}</td></tr>`:'';const statusBlock=hasExpected?`<div class="status">${reconciliation.status.toUpperCase()}</div>`:'';
    popup.document.write(`<!doctype html><html><head><title>HubVault Cash Summary</title><style>@page{size:${width}mm auto;margin:3mm}*{box-sizing:border-box}body{width:${width-6}mm;margin:0;font:11px monospace;color:#000}.center{text-align:center}h1{font-size:16px;margin:0}.line{border-top:1px dashed #000;margin:7px 0}table{width:100%;border-collapse:collapse}td{padding:2px 0}td:last-child{text-align:right}.total{font-size:13px;font-weight:bold}.status{border:1px solid #000;padding:5px;text-align:center;font-weight:bold;margin-top:6px}</style></head><body><div class="center"><h1>HUBVAULT</h1><div>Cash Count Summary</div></div><div class="line"></div>${nameLine}<div>Date: ${escapeHtml(date)}</div><div class="line"></div><table>${rows}</table><div class="line"></div><table><tr><td>Total Notes</td><td>${totalNotes}</td></tr><tr class="total"><td>Total Cash</td><td>Rs.${collected.toLocaleString('en-IN')}</td></tr>${reconciliationRows}</table>${statusBlock}<div class="line"></div><div class="center">Generated with HubVault<br>hubvault.in</div><script>window.onload=()=>window.print()</script></body></html>`);popup.document.close();
  };

  const reset=()=>{setResetBackup({name,date,expected,counts});setName('');setDate(localDate());setExpected('');applyCounts(emptyCounts());};
  const undoReset=()=>{if(!resetBackup)return;setName(resetBackup.name);setDate(resetBackup.date);setExpected(resetBackup.expected);setCounts(resetBackup.counts);setResetBackup(null);};
  const restoreSnapshot=(item:CashSnapshot)=>{setName(item.name);setDate(item.date);setExpected(item.expected);applyCounts(item.counts);};
  const calculatorSnapshot:CashSnapshot=useMemo(()=>({id:'current',name,date,expected,counts,total:collected,createdAt:new Date().toISOString()}),[name,date,expected,counts,collected]);
  const handleBrandingChange=useCallback((value:CashBranding)=>setBranding(value),[]);
  const statusStyles:Record<ReceiptStatus,string>={matched:'bg-emerald-500/15 text-emerald-100 border-emerald-300/30',shortage:'bg-red-500/20 text-red-100 border-red-300/30',excess:'bg-amber-400/20 text-amber-50 border-amber-200/30'};

  return <><SEO title={CASH_CALCULATOR_TITLE} description={CASH_CALCULATOR_DESCRIPTION} path="/tools/cash-calculator" image="https://www.hubvault.in/og-image-v2.jpg" structuredData={CASH_CALCULATOR_STRUCTURED_DATA} />
    <section className="relative min-h-screen overflow-hidden bg-[#f5f7ff] pb-28 dark:bg-[#080b16] md:pb-12">
      <div className="pointer-events-none absolute -left-32 top-20 h-80 w-80 rounded-full bg-violet-400/20 blur-3xl"/><div className="pointer-events-none absolute -right-32 top-0 h-96 w-96 rounded-full bg-cyan-300/20 blur-3xl"/>
      <div className="relative mx-auto w-full max-w-7xl px-2 py-3 min-[360px]:px-3 min-[360px]:py-5 sm:px-6 sm:py-8 lg:px-8 lg:py-12">
        {heroCollapsed&&<div className="mb-3 flex min-h-14 items-center justify-between gap-2 rounded-2xl bg-gradient-to-r from-[#211b50] to-[#4938ad] p-2 pl-3 text-white shadow-lg sm:hidden"><button onClick={()=>setHeroCollapsed(false)} className="flex min-w-0 flex-1 items-center gap-2 text-left" aria-label="Expand calculator introduction"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white/10"><Sparkles className="h-4 w-4 text-cyan-300"/></span><span className="truncate text-sm font-black">Smart Cash Calculator</span><ChevronDown className="ml-auto h-4 w-4 shrink-0 text-white/60"/></button><ThemeToggle className="shrink-0 border-white/20 !bg-white/10 !text-white hover:!border-cyan-300 hover:!text-cyan-300"/></div>}
        <header className={`${heroCollapsed?'hidden sm:block':'block'} relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#17152f] via-[#2f2370] to-[#5145cd] p-4 pt-16 text-white shadow-2xl shadow-indigo-900/20 min-[360px]:p-5 min-[360px]:pt-16 sm:p-8 lg:pt-8`}><div className="absolute right-3 top-3 flex items-center gap-1 rounded-2xl border border-white/10 bg-black/10 p-1.5 backdrop-blur min-[360px]:right-4 min-[360px]:top-4 min-[360px]:gap-2 lg:hidden"><button onClick={()=>setHeroCollapsed(true)} className="flex h-9 w-9 items-center justify-center rounded-xl text-white/70 hover:bg-white/10 hover:text-white sm:hidden" aria-label="Minimize calculator introduction"><ChevronUp className="h-4 w-4"/></button><span className="hidden pl-1 text-[10px] font-black uppercase tracking-wider text-white/60 min-[400px]:inline">Theme</span><ThemeToggle className="border-white/20 !bg-white/10 !text-white hover:!border-cyan-300 hover:!text-cyan-300"/></div>
          <div className="flex min-w-0 flex-col gap-5 sm:gap-7 lg:flex-row lg:items-end lg:justify-between"><div className="min-w-0 max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.12em] text-violet-100 min-[360px]:text-xs min-[360px]:tracking-[0.16em]"><Sparkles className="h-3.5 w-3.5"/>AI-assisted cash tool</span><h1 className="mt-4 text-[clamp(1.65rem,9vw,3rem)] font-black leading-[1.08] tracking-tight">Smart Cash Calculator<br/><span className="text-cyan-300">for Indian Currency</span></h1><p className="mt-3 max-w-xl text-sm leading-6 text-white/65 sm:text-base">Count rupee denominations by tap, Hindi or English voice, or editable photo OCR estimate. Reconcile expected cash and share a clear tally instantly.</p></div>
            <div className="min-w-0 rounded-3xl border border-white/15 bg-white/10 p-4 backdrop-blur-md sm:min-w-72"><p className="text-xs font-bold uppercase tracking-[0.18em] text-white/50">Live cash total</p><p className="mt-2 break-all text-[clamp(1.75rem,11vw,3rem)] font-black leading-none tracking-tight tabular-nums">{money(collected)}</p><div className="mt-3 flex items-center justify-between border-t border-white/10 pt-3 text-sm"><span className="text-white/55">Notes counted</span><span className="font-bold">{totalNotes}</span></div></div>
          </div>
        </header>

        <div className="relative -mt-2 mx-0 grid min-w-0 gap-3 rounded-3xl border border-white/80 bg-white/85 p-3 shadow-xl shadow-slate-200/50 backdrop-blur-xl dark:border-white/10 dark:bg-slate-900/85 dark:shadow-none min-[360px]:mx-2 sm:mx-5 sm:grid-cols-3 sm:p-4"><div className="flex items-center justify-between gap-2 sm:col-span-3"><span className={`rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-wider ${hasExpected?'bg-amber-100 text-amber-700 dark:bg-amber-400/15 dark:text-amber-300':'bg-emerald-100 text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-300'}`}>{hasExpected?'Reconciliation Mode':'Cash Count Mode'}</span><span className="text-[10px] font-semibold text-slate-400">Draft auto-saved on this device</span></div>
          <Field icon={<UserRound className="h-4 w-4"/>} label="Name (optional)"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Name" className="w-full bg-transparent text-sm font-semibold outline-none placeholder:font-normal placeholder:text-neutral-400"/></Field>
          <Field icon={<CalendarDays className="h-4 w-4"/>} label="Date"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="w-full bg-transparent text-sm font-semibold outline-none"/></Field>
          <Field icon={<Target className="h-4 w-4"/>} label="Expected (optional)"><input type="number" min={0} value={expected} onChange={e=>setExpected(e.target.value)} placeholder="₹0" className="w-full bg-transparent text-sm font-semibold outline-none placeholder:font-normal placeholder:text-neutral-400"/></Field>
        </div>

        <div className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]">
          <div className="min-w-0 rounded-3xl border border-white bg-white/80 p-2.5 shadow-xl shadow-slate-200/60 backdrop-blur dark:border-white/10 dark:bg-slate-900/70 dark:shadow-none min-[360px]:p-3 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3 px-1 pb-4"><div className="min-w-0"><p className="text-xs font-black uppercase tracking-[0.16em] text-brand-600">Denominations</p><h2 className="mt-1 text-lg font-black text-slate-900 min-[360px]:text-xl dark:text-white">Tap, type & count</h2></div><div className="flex items-center gap-1.5"><button onClick={undo} disabled={pastCounts.length===0} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 disabled:opacity-30 dark:border-white/10" aria-label="Undo"><Undo2 className="h-4 w-4"/></button><button onClick={redo} disabled={futureCounts.length===0} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 disabled:opacity-30 dark:border-white/10" aria-label="Redo"><Redo2 className="h-4 w-4"/></button><button disabled={totalNotes===0&&!name&&!expected} onClick={reset} className="inline-flex h-10 shrink-0 items-center gap-2 rounded-xl bg-red-600 px-3 text-xs font-black text-white shadow-lg shadow-red-600/25 transition hover:bg-red-700 active:scale-95 disabled:opacity-40 min-[360px]:h-11 min-[360px]:px-4"><RotateCcw className="h-4 w-4"/>Reset</button></div></div>
            <div className="mb-4 min-w-0 rounded-2xl border border-brand-200 bg-gradient-to-r from-brand-50 to-cyan-50 p-3 dark:border-slate-700 dark:!bg-[#151a2e] dark:bg-none dark:shadow-inner dark:shadow-black/20"><div className="flex min-w-0 flex-wrap items-center gap-2 min-[360px]:gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl shadow-lg ${listening?'animate-pulse bg-red-500 text-white shadow-red-500/20':'bg-brand-600 text-white shadow-brand-600/25'}`}>{listening?<Volume2 className="h-5 w-5"/>:<Mic className="h-5 w-5"/>}</span><div className="min-w-[120px] flex-1"><p className="text-sm font-black text-slate-800 dark:!text-slate-50">Voice-assisted entry</p><p className="truncate text-xs text-slate-500 dark:!text-slate-300">{voiceMessage}</p></div><div className="flex w-full justify-center rounded-xl bg-white p-1 shadow-sm min-[390px]:w-auto dark:!bg-[#252b42] dark:ring-1 dark:ring-white/10"><button onClick={()=>{setVoiceLanguage('en-IN');setVoiceMessage('Speak up to 9 denominations in one go');}} className={`flex-1 rounded-lg px-2.5 py-1.5 text-[11px] font-black min-[390px]:flex-none ${voiceLanguage==='en-IN'?'bg-brand-600 text-white shadow-sm':'text-slate-500 dark:!text-slate-300'}`}>EN</button><button onClick={()=>{setVoiceLanguage('hi-IN');setVoiceMessage('एक बार में 9 मूल्य तक बोलें');}} className={`flex-1 rounded-lg px-2.5 py-1.5 text-[11px] font-black min-[390px]:flex-none ${voiceLanguage==='hi-IN'?'bg-brand-600 text-white shadow-sm':'text-slate-500 dark:!text-slate-300'}`}>हिंदी</button></div></div><div className="mt-3 grid grid-cols-1 gap-2 min-[350px]:grid-cols-2"><button onClick={toggleVoice} className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-3 text-xs font-black transition ${listening?'bg-red-600 text-white hover:bg-red-700':'bg-white text-brand-700 shadow-sm hover:bg-brand-100 dark:!bg-brand-600 dark:!text-white dark:hover:!bg-brand-500'}`}>{listening?<><MicOff className="h-4 w-4"/>Stop</>:<><Mic className="h-4 w-4"/>{voiceLanguage==='hi-IN'?'बोलें':'Start voice'}</>}</button><button disabled={collected===0} onClick={()=>announceTotal()} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-slate-900 px-3 text-xs font-black text-white disabled:opacity-40 dark:!bg-cyan-300 dark:!text-slate-950 dark:disabled:!bg-slate-700 dark:disabled:!text-slate-300"><Volume2 className="h-4 w-4"/>{voiceLanguage==='hi-IN'?'कुल सुनें':'Hear live total'}</button></div></div>
            <div className="mb-4 grid gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-3 text-xs dark:border-white/10 dark:bg-white/[0.03] sm:grid-cols-2"><div className="sm:col-span-2"><label className="mb-1 block font-black text-slate-700 dark:text-slate-200">Recognized voice text</label><div className="flex gap-2"><input value={transcript} onChange={event=>setTranscript(event.target.value)} placeholder="Voice command appears here; edit it if needed" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-white px-3 py-2 outline-none focus:border-brand-500 dark:border-white/10 dark:bg-black/20"/><button disabled={!transcript.trim()} onClick={()=>applySpokenInput(transcript)} className="rounded-xl bg-brand-600 px-3 py-2 font-black text-white disabled:opacity-40">Apply</button></div></div><label className="flex items-center justify-between gap-2 rounded-xl bg-white px-3 py-2 dark:bg-black/20"><span className="inline-flex items-center gap-2">{soundEnabled?<Volume2 className="h-4 w-4"/>:<VolumeX className="h-4 w-4"/>}Sound announcements</span><input type="checkbox" checked={soundEnabled} onChange={event=>{setSoundEnabled(event.target.checked);if(!event.target.checked)window.speechSynthesis?.cancel();}}/></label><label className="flex items-center justify-between gap-2 rounded-xl bg-white px-3 py-2 dark:bg-black/20"><span>Continuous voice session</span><input type="checkbox" checked={continuousVoice} onChange={event=>setContinuousVoice(event.target.checked)}/></label><label className="rounded-xl bg-white px-3 py-2 dark:bg-black/20"><span className="flex justify-between"><span>Voice speed</span><strong>{voiceSpeed.toFixed(2)}x</strong></span><input aria-label="Voice speed" type="range" min="0.6" max="1.4" step="0.05" value={voiceSpeed} onChange={event=>setVoiceSpeed(Number(event.target.value))} className="mt-2 w-full accent-brand-600"/></label><label className="rounded-xl bg-white px-3 py-2 dark:bg-black/20"><span className="flex justify-between"><span>Volume</span><strong>{Math.round(voiceVolume*100)}%</strong></span><input aria-label="Voice volume" type="range" min="0" max="1" step="0.05" value={voiceVolume} onChange={event=>setVoiceVolume(Number(event.target.value))} className="mt-2 w-full accent-brand-600"/></label><p className="sm:col-span-2 text-[11px] leading-5 text-slate-500 dark:text-slate-400">Privacy: voice recognition is handled by your browser. Drafts and history stay on this device and are not uploaded to HubVault servers.</p></div>
            <div className="grid grid-cols-1 gap-2.5 min-[390px]:grid-cols-2 sm:grid-cols-3">{NOTES.map((note,index)=>{const active=counts[note]>0;return <article key={note} className={`relative min-w-0 overflow-hidden rounded-2xl border p-3 transition-all ${active?'border-brand-500 bg-brand-50 shadow-lg shadow-brand-500/10 dark:!border-violet-500 dark:!bg-[#282052] dark:shadow-violet-950/40':'border-slate-200 bg-white hover:border-brand-300 dark:border-white/10 dark:bg-white/[0.03]'}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-xl font-black tracking-tight ${active?'text-brand-700 dark:text-violet-200':'text-slate-800 dark:text-slate-100'}`}>₹{note}</p><p className={`mt-0.5 text-[10px] font-bold uppercase tracking-wider ${active?'text-brand-500 dark:text-violet-300':'text-slate-400'}`}>Quantity {counts[note]}</p></div><p className={`max-w-[96px] truncate text-right text-sm font-black tabular-nums ${active?'text-brand-700 dark:text-cyan-300':'text-slate-500 dark:text-slate-300'}`}>{money(note*counts[note])}</p></div><div className="mt-3 flex min-w-0 items-center rounded-xl bg-slate-100 p-1 dark:bg-black/25"><button aria-label={`Decrease ₹${note}`} onClick={()=>adjust(note,-1)} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg text-slate-500 transition hover:bg-white hover:text-brand-600 hover:shadow-sm dark:hover:bg-white/10"><Minus className="h-4 w-4"/></button><input data-note-index={index} aria-label={`₹${note} note quantity`} type="number" inputMode="numeric" min={0} value={counts[note]||''} placeholder="0" onChange={e=>setCount(note,e.target.value)} onKeyDown={e=>focusNext(e,index)} className="h-9 min-w-0 flex-1 bg-transparent px-1 text-center text-lg font-black tabular-nums outline-none"/><button aria-label={`Increase ₹${note}`} onClick={()=>adjust(note,1)} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-brand-600 text-xl font-medium text-white shadow-md shadow-brand-600/25 transition hover:bg-brand-700 active:scale-90">+</button></div></article>})}</div>
          </div>

          <div className="min-w-0 space-y-4 lg:sticky lg:top-20"><aside className="h-fit min-w-0 overflow-hidden rounded-3xl bg-[#111327] text-white shadow-2xl shadow-slate-900/20"><div className="border-b border-white/10 p-4 min-[360px]:p-5"><div className="flex min-w-0 flex-wrap items-center justify-between gap-2"><div className="min-w-0"><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-300">Cash summary</p><p className="mt-1 break-all text-[clamp(1.6rem,10vw,1.875rem)] font-black tabular-nums">{money(collected)}</p></div>{hasExpected&&<span className={`rounded-full border px-3 py-1 text-[10px] font-black tracking-wider ${statusStyles[reconciliation.status]}`}>{reconciliation.status.toUpperCase()}</span>}</div><div className="mt-5 grid grid-cols-1 gap-2 min-[340px]:grid-cols-2">{hasExpected&&<Metric label="Expected" value={money(expectedAmount)}/>}<Metric label="Total notes" value={String(totalNotes)}/>{hasExpected&&<Metric label="Variance" value={`${reconciliation.variance<0?'-':reconciliation.variance>0?'+':''}${money(reconciliation.variance)}`}/>}<Metric label="Entries" value={String(NOTES.filter(note=>counts[note]>0).length)}/></div></div>
            <div className="grid gap-2 p-4"><button disabled={totalNotes===0} onClick={copyWhatsApp} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-cyan-300 px-4 text-sm font-black text-slate-950 transition hover:bg-cyan-200 disabled:opacity-30">{copied?<Check className="h-4 w-4"/>:<Clipboard className="h-4 w-4"/>}{copied?'Summary Copied':'Copy WhatsApp Summary'}</button><div className="grid grid-cols-2 gap-2"><button disabled={totalNotes===0} onClick={shareReceipt} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-white/10 px-3 text-xs font-bold transition hover:bg-white/15 disabled:opacity-30"><Share2 className="h-4 w-4"/>Share</button><button disabled={totalNotes===0} onClick={downloadPdf} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-white/10 px-3 text-xs font-bold transition hover:bg-white/15 disabled:opacity-30"><FileDown className="h-4 w-4"/>PDF</button></div><div className="grid grid-cols-2 gap-2"><button disabled={totalNotes===0} onClick={()=>printThermal(58)} className="inline-flex min-h-11 items-center justify-center gap-1.5 rounded-xl border border-white/10 px-2 text-xs font-semibold text-white/70 transition hover:bg-white/5 disabled:opacity-30"><Printer className="h-3.5 w-3.5"/>2-inch</button><button disabled={totalNotes===0} onClick={()=>printThermal(80)} className="inline-flex min-h-11 items-center justify-center gap-1.5 rounded-xl border border-white/10 px-2 text-xs font-semibold text-white/70 transition hover:bg-white/5 disabled:opacity-30"><Printer className="h-3.5 w-3.5"/>3-inch</button></div></div>
          </aside><LiveDenominationBreakdown counts={counts} total={collected}/></div>
        </div>
        <CashCalculatorTools snapshot={calculatorSnapshot} onRestore={restoreSnapshot} onApplyCounts={applyCounts} onBrandingChange={handleBrandingChange}/>
        <SmartCashFeatures/>
        <section aria-labelledby="cash-calculator-guide" className="mt-5 rounded-3xl border border-slate-200 bg-white/85 p-4 shadow-xl shadow-slate-200/40 dark:border-white/10 dark:bg-slate-900/70 dark:shadow-none sm:p-7"><div className="mx-auto max-w-5xl"><p className="text-xs font-black uppercase tracking-[.16em] text-brand-600">Free Indian cash tally tool</p><h2 id="cash-calculator-guide" className="mt-2 text-2xl font-black text-slate-900 dark:text-white sm:text-3xl">How to use the cash denomination calculator</h2><ol className="mt-4 grid gap-3 text-sm leading-6 text-slate-600 dark:text-slate-300 md:grid-cols-3"><li className="rounded-2xl bg-slate-50 p-4 dark:bg-white/5"><b className="block text-slate-900 dark:text-white">1. Enter note quantities</b>Type or tap the number of notes for each Indian currency denomination.</li><li className="rounded-2xl bg-slate-50 p-4 dark:bg-white/5"><b className="block text-slate-900 dark:text-white">2. Add expected cash</b>Optionally enter the expected amount to activate reconciliation mode.</li><li className="rounded-2xl bg-slate-50 p-4 dark:bg-white/5"><b className="block text-slate-900 dark:text-white">3. Verify and share</b>Review the total, shortage or excess, then copy, print or export the summary.</li></ol><div className="mt-7 grid gap-6 md:grid-cols-2"><article><h2 className="text-xl font-black text-slate-900 dark:text-white">Supported Indian currency denominations</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Count ₹500, ₹200, ₹100, ₹50, ₹20, ₹10, ₹5, ₹2 and ₹1 notes or coins. Each quantity updates the total instantly and can be corrected with undo, direct entry or voice commands.</p></article><article><h2 className="text-xl font-black text-slate-900 dark:text-white">COD and logistics cash reconciliation</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Delivery hubs, riders and cashiers can compare expected COD collections with physically counted cash. HubVault clearly shows a matched amount, shortage or excess for faster daily closing and handover verification.</p></article></div><div className="mt-8"><h2 className="text-xl font-black text-slate-900 dark:text-white">Frequently asked questions</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{CASH_CALCULATOR_FAQS.map(item=><details key={item.question} className="rounded-2xl border border-slate-200 p-4 dark:border-white/10"><summary className="cursor-pointer text-sm font-black text-slate-900 dark:text-white">{item.question}</summary><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{item.answer}</p></details>)}</div></div></div></section>
        {resetBackup&&<div className="fixed bottom-20 left-1/2 z-50 flex w-[min(92vw,420px)] -translate-x-1/2 items-center justify-between gap-3 rounded-2xl bg-slate-950 px-4 py-3 text-sm font-bold text-white shadow-2xl md:bottom-5"><span>Calculation reset</span><button onClick={undoReset} className="inline-flex items-center gap-2 rounded-xl bg-white/15 px-3 py-2 text-cyan-300 hover:bg-white/20"><Undo2 className="h-4 w-4"/>Undo</button></div>}
        <div className="fixed inset-x-3 bottom-3 z-40 flex items-center justify-between gap-3 rounded-2xl border border-white/10 bg-[#111327]/95 px-4 py-3 text-white shadow-2xl backdrop-blur-xl md:hidden"><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-wider text-cyan-300">Live total</p><p className="truncate text-xl font-black tabular-nums">{money(collected)}</p></div>{hasExpected?<div className="shrink-0 text-right"><span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-bold ${statusStyles[reconciliation.status]}`}>{reconciliation.status.toUpperCase()}</span><p className="mt-1 text-[11px] text-white/60">Variance {reconciliation.variance<0?'-':reconciliation.variance>0?'+':''}{money(reconciliation.variance)}</p></div>:<div className="shrink-0 text-right"><p className="text-[10px] uppercase tracking-wider text-white/40">Notes</p><p className="text-lg font-black tabular-nums">{totalNotes}</p></div>}</div>
      </div>
    </section></>;
}

const NOTE_COLORS:Record<NoteValue,string>={500:'from-stone-500 to-stone-700',200:'from-amber-500 to-orange-600',100:'from-violet-500 to-purple-700',50:'from-cyan-500 to-blue-600',20:'from-lime-500 to-emerald-600',10:'from-amber-400 to-yellow-600',5:'from-emerald-500 to-teal-700',2:'from-sky-500 to-indigo-600',1:'from-slate-500 to-slate-700'};
function LiveDenominationBreakdown({counts,total}:{counts:Record<NoteValue,number>;total:number}){const maxAmount=Math.max(...NOTES.map(note=>note*counts[note]),1);return <section aria-label="Live denomination calculation" className="overflow-hidden rounded-3xl border border-slate-200 bg-white p-4 shadow-xl shadow-slate-200/50 dark:border-white/10 dark:bg-slate-900 dark:shadow-none"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-brand-600 dark:text-cyan-300">Live calculation</p><h2 className="mt-1 text-lg font-black text-slate-900 dark:text-white">Denomination breakdown</h2></div><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-brand-50 text-brand-600 dark:bg-cyan-300/10 dark:text-cyan-300"><Banknote className="h-6 w-6"/></div></div><div className="mt-4 space-y-2">{NOTES.map(note=>{const quantity=counts[note];const amount=note*quantity;const active=quantity>0;return <div key={note} className={`relative overflow-hidden rounded-2xl border p-2.5 transition ${active?'border-brand-200 bg-brand-50/70 dark:border-violet-400/30 dark:bg-violet-500/10':'border-slate-100 bg-slate-50/70 dark:border-white/5 dark:bg-white/[.025]'}`}><div className="relative z-10 flex items-center gap-3"><span className={`relative flex h-10 w-16 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-gradient-to-br ${NOTE_COLORS[note]} text-white shadow-sm`}><Banknote className="absolute h-9 w-12 opacity-30"/><b className="relative text-sm">₹{note}</b></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className={`text-xs font-bold ${active?'text-slate-800 dark:text-white':'text-slate-400 dark:text-slate-500'}`}>₹{note} × {quantity}</p><p className={`truncate text-sm font-black tabular-nums ${active?'text-brand-700 dark:text-cyan-300':'text-slate-400 dark:text-slate-500'}`}>{money(amount)}</p></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-slate-200 dark:bg-white/10"><div className={`h-full rounded-full bg-gradient-to-r ${NOTE_COLORS[note]} transition-all duration-300`} style={{width:`${amount?Math.max(7,(amount/maxAmount)*100):0}%`}}/></div></div></div></div>})}</div><div className="mt-4 flex items-center justify-between rounded-2xl bg-[#111327] px-4 py-3 text-white"><span className="text-xs font-bold uppercase tracking-wider text-white/50">Calculated total</span><strong className="text-xl font-black tabular-nums text-cyan-300">{money(total)}</strong></div></section>}

function SmartCashFeatures(){const features=[
  ['Hindi & English voice counting','Speak up to nine denomination quantities in one command, edit the recognized text, hear every update and ask for the live total.'],
  ['Photo OCR cash estimate','Take or upload a clear cash photo to get editable, browser-based denomination suggestions. Always physically verify the estimate.'],
  ['Automatic cash reconciliation','Compare expected and counted cash to instantly identify an exact match, shortage or excess—useful for COD, cashier and daily closing.'],
  ['Bundles, presets & multiple bags','Add sealed 100-note bundles, reuse common denomination presets, save separate bags or counters and see their combined grand total.'],
  ['PDF, Excel & thermal receipts','Download branded cash-count reports, export denomination rows to Excel, or print 2-inch and 3-inch thermal receipts.'],
  ['WhatsApp, QR & shareable links','Copy a WhatsApp-ready summary, use your device share sheet, or hand over the calculation through a link or QR code.'],
  ['Private local drafts & history','Drafts, branding, presets and up to 20 saved calculations stay in your browser unless you deliberately share a link.'],
  ['Installable smart cash tool','Add HubVault to your home screen for quick repeat access on mobile or desktop, with undo, redo and recoverable reset.'],
];return <section aria-labelledby="smart-cash-features" className="mt-5 rounded-3xl border border-slate-200 bg-white/85 p-4 shadow-xl shadow-slate-200/40 dark:border-white/10 dark:bg-slate-900/70 dark:shadow-none sm:p-7"><div className="mx-auto max-w-5xl"><p className="text-xs font-black uppercase tracking-[.16em] text-brand-600">AI-assisted, human-verified</p><h2 id="smart-cash-features" className="mt-2 text-2xl font-black text-slate-900 dark:text-white sm:text-3xl">Smart cash calculator features</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-300">HubVault combines fast Indian currency counting with voice assistance, OCR suggestions, cash reconciliation and professional sharing tools. Voice and photo results remain editable so the final cash count stays under your control.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{features.map(([title,description])=><article key={title} className="rounded-2xl bg-slate-50 p-4 dark:bg-white/5"><h3 className="font-black text-slate-900 dark:text-white">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600 dark:text-slate-300">{description}</p></article>)}</div></div></section>}

function Metric({label,value}:{label:string;value:string}){return <div className="min-w-0 rounded-2xl border border-white/5 bg-white/[0.06] p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-white/40">{label}</p><p className="mt-1 break-all font-black tabular-nums">{value}</p></div>;}
function Field({icon,label,children}:{icon:React.ReactNode;label:string;children:React.ReactNode}){return <label className="flex min-w-0 overflow-hidden items-center gap-3 rounded-2xl border border-slate-200/80 bg-white px-3 py-3 transition focus-within:border-brand-400 focus-within:ring-4 focus-within:ring-brand-500/10 dark:border-white/10 dark:bg-white/[0.04] min-[360px]:px-3.5"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/15 dark:text-brand-300">{icon}</span><span className="min-w-0 flex-1 [&>input]:min-w-0"><span className="mb-0.5 block truncate text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</span>{children}</span></label>;}
