import SEO from '@/components/SEO';
import { ArrowRight, Building2, CheckCircle2, ClipboardCheck, Eye, Landmark, Mail, ShieldCheck, Target, UsersRound, WalletCards } from 'lucide-react';

const URL='https://www.hubvault.in/about';
const BUY_URL='/#/buy-now';
const CONTACT_URL='/#/contact';
const DESCRIPTION='Learn about HubVault, a logistics collection reconciliation platform for COD cash, online payments, CMS deposits, daily closing, employee dues and recovery.';
const STRUCTURED_DATA=[
  {'@context':'https://schema.org','@type':'Organization','@id':'https://www.hubvault.in/#organization',name:'HubVault',url:'https://www.hubvault.in/',logo:'https://www.hubvault.in/og-image-v2.jpg',image:'https://www.hubvault.in/og-image-v2.jpg',description:DESCRIPTION,email:'hello@hubvault.in',contactPoint:[{'@type':'ContactPoint',contactType:'sales',email:'sales@hubvault.in',availableLanguage:['English','Hindi']},{'@type':'ContactPoint',contactType:'customer support',email:'support@hubvault.in',availableLanguage:['English','Hindi']}]},
  {'@context':'https://schema.org','@type':'AboutPage',url:URL,name:'About HubVault',description:DESCRIPTION,mainEntity:{'@id':'https://www.hubvault.in/#organization'}},
];
const VALUES=[
  {icon:Eye,title:'Operational visibility',text:'Give management a clear, date-wise view of collections, deposits, variance and recovery across each hub.'},
  {icon:ShieldCheck,title:'Accountable records',text:'Keep role-based actions, approvals and audit history attached to the people responsible for them.'},
  {icon:ClipboardCheck,title:'Practical reconciliation',text:'Connect expected amounts, actual cash, online payments and exceptions in one repeatable workflow.'},
];

export default function OrganizationPage(){return <>
  <SEO title="About HubVault – Logistics Collection Reconciliation Software" description={DESCRIPTION} path="/about" image="https://www.hubvault.in/og-image-v2.jpg" structuredData={STRUCTURED_DATA}/>
  <main className="overflow-hidden bg-white text-slate-900 dark:bg-[#080b16] dark:text-white">
    <section className="relative isolate border-b border-slate-200 dark:border-white/10"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_18%_15%,rgba(79,70,229,.24),transparent_35%),radial-gradient(circle_at_88%_25%,rgba(6,182,212,.16),transparent_30%)]"/><div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:px-8 lg:py-28"><div><p className="text-xs font-black uppercase tracking-[.18em] text-indigo-600 dark:text-indigo-300">About HubVault</p><h1 className="mt-4 text-4xl font-black leading-[1.08] tracking-tight sm:text-5xl lg:text-6xl">Helping logistics teams account for <span className="bg-gradient-to-r from-indigo-600 to-cyan-500 bg-clip-text text-transparent">every rupee collected.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">HubVault is a web-based collection reconciliation platform for logistics and delivery operations. It connects COD cash, online payments, CMS deposits, shortages, employee dues, recovery and daily closing.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={BUY_URL} className="inline-flex min-h-13 items-center justify-center gap-2 rounded-2xl bg-indigo-600 px-7 py-3.5 text-sm font-black text-white shadow-xl shadow-indigo-600/25 transition hover:bg-indigo-700">Buy HubVault <ArrowRight className="h-4 w-4"/></a><a href={CONTACT_URL} className="inline-flex min-h-13 items-center justify-center gap-2 rounded-2xl border border-slate-300 px-7 py-3.5 text-sm font-black dark:border-white/15"><Mail className="h-4 w-4"/>Contact us</a></div></div><div className="relative"><div className="absolute -inset-6 rounded-[2.5rem] bg-indigo-500/20 blur-3xl"/><div className="relative rounded-[2rem] border border-white/10 bg-[#111327] p-6 text-white shadow-2xl sm:p-8"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-indigo-500"><Building2 className="h-7 w-7"/></div><p className="mt-6 text-xs font-black uppercase tracking-[.16em] text-cyan-300">HubVault reconciliation suite</p><h2 className="mt-2 text-2xl font-black">One connected operational record</h2><div className="mt-6 space-y-3">{['Collector-wise cash and online collection','CMS deposition records','Daily closing approval and reporting','Employee dues and recovery history'].map(item=><div key={item} className="flex items-center gap-3 rounded-2xl bg-white/[.06] p-4 text-sm font-bold"><CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-300"/>{item}</div>)}</div></div></div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-20 lg:px-8"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[.18em] text-indigo-600">Why HubVault exists</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Replace fragmented collection tracking with clarity</h2><p className="mt-5 leading-7 text-slate-600 dark:text-slate-300">Many logistics hubs still reconcile daily collections through paper notes, messages and disconnected spreadsheets. That makes shortages harder to investigate, deposits harder to verify and management reporting slower. HubVault was created to turn that fragmented process into an accurate and auditable workflow.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{VALUES.map(item=><article key={item.title} className="rounded-3xl border border-slate-200 bg-slate-50/70 p-6 dark:border-white/10 dark:bg-white/[.04]"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-100 text-indigo-700 dark:bg-indigo-400/10 dark:text-indigo-300"><item.icon className="h-6 w-6"/></span><h3 className="mt-5 text-lg font-black">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{item.text}</p></article>)}</div></section>

    <section className="bg-slate-950 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 sm:py-20 lg:grid-cols-2 lg:items-center lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Who HubVault serves</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Designed for cash-intensive logistics operations</h2><p className="mt-4 leading-7 text-white/65">HubVault supports teams that collect COD through riders or employees and need reliable handover, deposit, approval and recovery records.</p><ul className="mt-7 space-y-4">{['Courier and delivery hubs','Last-mile logistics operations','COD collection supervisors','Multi-hub reconciliation teams'].map(item=><li key={item} className="flex gap-3 text-sm font-bold text-white/80"><CheckCircle2 className="h-5 w-5 text-cyan-300"/>{item}</li>)}</ul></div><div className="grid gap-4 sm:grid-cols-2"><Capability icon={<WalletCards/>} title="Collections" text="Cash and online amounts remain clearly separated."/><Capability icon={<Landmark/>} title="Deposits" text="CMS deposition details retain their operational context."/><Capability icon={<UsersRound/>} title="Roles" text="Administrators and supervisors work through controlled access."/><Capability icon={<ShieldCheck/>} title="Auditability" text="Approvals, corrections and recovery remain traceable."/></div></div></section>

    <section className="mx-auto grid max-w-7xl gap-6 px-4 py-16 sm:px-6 sm:py-20 md:grid-cols-2 lg:px-8"><article className="rounded-[2rem] border border-slate-200 p-7 dark:border-white/10"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-100 text-indigo-700 dark:bg-indigo-400/10 dark:text-indigo-300"><Target className="h-6 w-6"/></span><h2 className="mt-5 text-2xl font-black">Our mission</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">Help logistics teams reduce manual collection errors, understand operational variance quickly and close every day with reliable financial records.</p></article><article className="rounded-[2rem] border border-slate-200 p-7 dark:border-white/10"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-100 text-cyan-700 dark:bg-cyan-400/10 dark:text-cyan-300"><Eye className="h-6 w-6"/></span><h2 className="mt-5 text-2xl font-black">Our vision</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">A logistics industry where every collected amount can be tracked, verified and reconciled without spreadsheet confusion.</p></article></section>

    <section className="px-4 pb-16 sm:px-6 sm:pb-20"><div className="mx-auto max-w-6xl rounded-[2rem] bg-gradient-to-r from-indigo-700 to-violet-700 px-6 py-12 text-center text-white sm:px-10 sm:py-16"><h2 className="text-3xl font-black sm:text-4xl">Ready to bring clarity to daily collections?</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-white/70">Explore HubVault through the official buying page or contact the team at hello@hubvault.in.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><a href={BUY_URL} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-white px-6 text-sm font-black text-indigo-700">View pricing & buy <ArrowRight className="h-4 w-4"/></a><a href="mailto:hello@hubvault.in" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl border border-white/20 px-6 text-sm font-black"><Mail className="h-4 w-4"/>hello@hubvault.in</a></div></div></section>
  </main>
</>}

function Capability({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className="rounded-3xl border border-white/10 bg-white/[.06] p-5"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo-400/15 text-indigo-200 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{text}</p></article>}
