import { Executive, VehicleType } from '@/lib/routeLoad/types';
import { Lock, Plus, Trash2, Unlock } from 'lucide-react';

const vehicles:VehicleType[]=['Bike','Cycle','EV','Van','Walking','Other'];
const num=(v:string)=>Math.max(0,Math.floor(Number(v)||0));
export default function ExecutiveSetup({executives,onChange}:{executives:Executive[];onChange:(value:Executive[])=>void}){
  const update=<K extends keyof Executive>(id:string,key:K,value:Executive[K])=>onChange(executives.map(e=>e.id===id?{...e,[key]:value}:e));
  const add=()=>onChange([...executives,{id:crypto.randomUUID(),name:`Executive ${executives.length+1}`,employeeId:'',route:'',area:'',pincodes:[],maxCapacity:40,pendingLoad:0,vehicle:'Bike',active:true}]);
  return <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-slate-900/70 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-brand-600">Delivery team</p><h2 className="mt-1 text-xl font-black text-slate-900 dark:text-white">Configure executives</h2></div><button onClick={add} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-brand-600 px-4 text-sm font-black text-white"><Plus className="h-4 w-4"/>Add Executive</button></div>
  <div className="mt-5 space-y-4">{executives.length===0?<div className="rounded-2xl border border-dashed border-slate-300 py-10 text-center text-sm text-slate-500 dark:border-slate-700">Add at least one delivery executive.</div>:executives.map((e,index)=><article key={e.id} className="rounded-2xl border border-slate-200 p-4 dark:border-white/10"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-indigo-50 text-xs font-black text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300">{index+1}</span><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={e.active} onChange={x=>update(e.id,'active',x.target.checked)}/> Available</label></div><div className="flex gap-1"><button title={e.locked?'Unlock assignments':'Lock assignments'} onClick={()=>update(e.id,'locked',!e.locked)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 dark:hover:bg-white/10">{e.locked?<Lock className="h-4 w-4"/>:<Unlock className="h-4 w-4"/>}</button><button title="Remove executive" onClick={()=>onChange(executives.filter(x=>x.id!==e.id))} className="rounded-lg p-2 text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10"><Trash2 className="h-4 w-4"/></button></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
  <Field label="Executive name *"><input value={e.name} onChange={x=>update(e.id,'name',x.target.value)} className="input-base"/></Field><Field label="Employee ID"><input value={e.employeeId} onChange={x=>update(e.id,'employeeId',x.target.value)} className="input-base"/></Field><Field label="Route"><input value={e.route} onChange={x=>update(e.id,'route',x.target.value)} className="input-base" placeholder="BGU-02"/></Field><Field label="Area"><input value={e.area} onChange={x=>update(e.id,'area',x.target.value)} className="input-base" placeholder="Begusarai Town"/></Field><Field label="Pincodes (comma separated)"><input value={e.pincodes.join(', ')} onChange={x=>update(e.id,'pincodes',x.target.value.split(',').map(p=>p.trim()).filter(Boolean))} className="input-base" placeholder="851101, 851129"/></Field><Field label="Maximum capacity *"><input type="number" min="0" step="1" value={e.maxCapacity} onChange={x=>update(e.id,'maxCapacity',num(x.target.value))} className="input-base"/></Field><Field label="Current pending load"><input type="number" min="0" step="1" value={e.pendingLoad} onChange={x=>update(e.id,'pendingLoad',num(x.target.value))} className="input-base"/></Field><Field label="Vehicle"><select value={e.vehicle} onChange={x=>update(e.id,'vehicle',x.target.value as VehicleType)} className="input-base">{vehicles.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Maximum COD (optional)"><input type="number" min="0" value={e.maxCodAmount??''} onChange={x=>update(e.id,'maxCodAmount',x.target.value===''?undefined:Number(x.target.value))} className="input-base"/></Field><Field label="Maximum weight (kg)"><input type="number" min="0" value={e.maxWeight??''} onChange={x=>update(e.id,'maxWeight',x.target.value===''?undefined:Number(x.target.value))} className="input-base"/></Field>
  </div></article>)}</div></section>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600 dark:text-slate-300">{label}</span>{children}</label>}
