import { DistributionResult, DistributionSettings, Executive } from '@/lib/routeLoad/types';
import { Download, Eye, FileDown, Lock, Printer, RotateCcw, Search, X } from 'lucide-react';
import { useMemo, useState } from 'react';

interface Props {result:DistributionResult;executives:Executive[];settings:DistributionSettings;selected:Set<string>;onSelected:(value:Set<string>)=>void;onMove:(executiveId:string|null)=>void;onExport:()=>void;onCsv:()=>void;onExecutiveExport:(id:string)=>void;onReset:()=>void;onToggleLock:(id:string)=>void;onRedistributeUnlocked:()=>void;onReview:(awb:string,executiveId:string|null,decision:'confirm'|'reject')=>void}

export default function ResultsDashboard(props:Props){
  const {result,executives,settings,selected,onSelected,onMove,onExport,onCsv,onExecutiveExport,onReset,onToggleLock,onRedistributeUnlocked,onReview}=props;
  const [search,setSearch]=useState('');const [executive,setExecutive]=useState('all');const [status,setStatus]=useState('all');const [priority,setPriority]=useState('all');const [reviewingAwb,setReviewingAwb]=useState('');const [reviewEmployee,setReviewEmployee]=useState('');
  const reviewing=result.assignments.find(item=>item.shipment.awb===reviewingAwb);
  const visible=useMemo(()=>result.assignments.filter(a=>(executive==='all'||(executive==='unassigned'?a.executiveId===null:a.executiveId===executive))&&(status==='all'||a.status===status)&&(priority==='all'||a.shipment.priority===priority)&&`${a.shipment.awb} ${executives.find(e=>e.id===a.executiveId)?.name??'unassigned'}`.toLowerCase().includes(search.toLowerCase())),[result,executives,search,executive,status,priority]);
  const active=executives.filter(e=>e.active).length;const cards:[string,string|number][]=[['Total Shipments',result.total],['Assigned',result.assigned],['Pincode Review',result.review],['Unassigned',result.unassigned],['Active Executives',active],['Available Capacity',result.totalCapacity],['Capacity Utilization',`${result.utilization.toFixed(1)}%`],['Total COD',`₹${result.totalCod.toLocaleString('en-IN')}`]];
  const toggle=(awb:string,checked:boolean)=>{const next=new Set(selected);if(checked)next.add(awb);else next.delete(awb);onSelected(next);};
  const openReview=(awb:string,employeeId:string|null)=>{setReviewingAwb(awb);setReviewEmployee(employeeId??'');};
  const closeReview=()=>{setReviewingAwb('');setReviewEmployee('');};
  return <section className="space-y-5" id="distribution-results">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-600">Distribution complete</p><h2 className="text-2xl font-black">Results dashboard</h2></div><div className="flex flex-wrap gap-2"><button onClick={onRedistributeUnlocked} className="action"><RotateCcw/>Redistribute unlocked</button><button onClick={onExport} className="action"><Download/>Excel report</button><button onClick={onCsv} className="action"><FileDown/>CSV</button><button onClick={()=>window.print()} className="action"><Printer/>Print</button><button onClick={onReset} className="action"><RotateCcw/>Reset</button></div></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{cards.map(([label,value])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-slate-900"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>)}</div>
    <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-slate-900"><h3 className="font-black">Executive load</h3><div className="mt-4 space-y-4">{result.executiveResults.map(r=><div key={r.executive.id}><div className="mb-1 flex justify-between text-xs"><button onClick={()=>onToggleLock(r.executive.id)} className="font-bold">{r.executive.name}{r.executive.locked&&<Lock className="ml-1 inline h-3 w-3"/>}</button><span>{r.finalLoad}/{r.executive.maxCapacity} · {r.utilization.toFixed(0)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-white/10"><div className={`h-full ${r.utilization>=100?'bg-red-500':r.utilization>=85?'bg-amber-500':'bg-emerald-500'}`} style={{width:`${Math.min(100,r.utilization)}%`}}/></div></div>)}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-slate-900"><h3 className="font-black">Assignment coverage</h3><div className="mt-5 space-y-3 text-sm"><p><b className="text-emerald-600">{result.assigned}</b> confirmed assignments</p><p><b className="text-violet-600">{result.review}</b> pincode matches awaiting review</p><p><b className="text-amber-600">{result.unassigned}</b> unassigned</p><p className="text-xs text-slate-500">COD balance: {settings.balanceCod?'On':'Off'} · Weight limits: {settings.considerWeight?'On':'Off'}</p></div></div></div>
    <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white dark:border-white/10 dark:bg-slate-900"><div className="border-b border-slate-200 p-4 dark:border-white/10"><div className="flex flex-col gap-3 xl:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className="input-base pl-9" placeholder="Search AWB or executive"/></label><select className="input-base xl:w-52" value={executive} onChange={e=>setExecutive(e.target.value)}><option value="all">All executives</option><option value="unassigned">Unassigned</option>{executives.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select><select className="input-base xl:w-40" value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">All priority</option>{['Urgent','High','Normal','Low'].map(p=><option key={p}>{p}</option>)}</select><select className="input-base xl:w-40" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All status</option><option>Assigned</option><option>Review</option><option>Unassigned</option></select></div>{selected.size>0&&<div className="mt-3 flex items-center gap-2 rounded-xl bg-indigo-50 p-3 text-sm dark:bg-indigo-500/10"><b>{selected.size} selected</b><select className="input-base ml-auto sm:w-60" defaultValue="" onChange={e=>{if(e.target.value){onMove(e.target.value==='unassigned'?null:e.target.value);e.target.value='';}}}><option value="" disabled>Move selected to…</option><option value="unassigned">Unassigned</option>{executives.filter(e=>e.active).map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></div>}</div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1350px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500 dark:bg-white/5"><tr>{['','S.No','AWB','Executive','Employee ID','Route','Area','Pincode','Priority','Payment','COD','Weight','Reason','Status','Action'].map(x=><th className="px-3 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{visible.map((a,i)=>{const e=executives.find(x=>x.id===a.executiveId);return <tr key={a.shipment.awb} className="border-t border-slate-100 dark:border-white/5"><td className="px-3"><input type="checkbox" checked={selected.has(a.shipment.awb)} onChange={x=>toggle(a.shipment.awb,x.target.checked)}/></td><td className="px-3 py-3">{i+1}</td><td className="px-3 py-3 font-mono font-bold">{a.shipment.awb}</td><td className="px-3 py-3 font-bold">{e?.name??'Unassigned'}</td><td className="px-3 py-3">{e?.employeeId||'—'}</td><td className="px-3 py-3">{a.shipment.route||'—'}</td><td className="px-3 py-3">{a.shipment.area||'—'}</td><td className="px-3 py-3">{a.shipment.pincode||'—'}</td><td className="px-3 py-3">{a.shipment.priority}</td><td className="px-3 py-3">{a.shipment.paymentType}</td><td className="px-3 py-3">₹{a.shipment.codAmount.toLocaleString('en-IN')}</td><td className="px-3 py-3">{a.shipment.weight||'—'}</td><td className="px-3 py-3">{a.reason}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 font-bold ${a.status==='Assigned'?'bg-emerald-50 text-emerald-700':a.status==='Review'?'bg-violet-50 text-violet-700':'bg-amber-50 text-amber-700'}`}>{a.status}</span></td><td className="px-3 py-3">{a.status==='Review'&&<button onClick={()=>openReview(a.shipment.awb,a.executiveId)} className="inline-flex items-center gap-1 rounded-lg bg-violet-600 px-3 py-2 font-black text-white"><Eye className="h-3.5 w-3.5"/>Review</button>}</td></tr>})}</tbody></table></div></div>
    <div className="flex flex-wrap gap-2">{result.executiveResults.filter(r=>r.newLoad>0).map(r=><button key={r.executive.id} onClick={()=>onExecutiveExport(r.executive.id)} className="action"><FileDown/>Download {r.executive.name}</button>)}</div>
    {reviewing&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/60 p-3 backdrop-blur-sm"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl dark:bg-slate-900 sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-violet-600">Pincode match verification</p><h3 className="mt-1 text-xl font-black">Review customer address</h3><p className="mt-1 font-mono text-xs">{reviewing.shipment.awb}</p></div><button onClick={closeReview} className="rounded-xl p-2 hover:bg-slate-100 dark:hover:bg-white/10"><X className="h-5 w-5"/></button></div><div className="mt-5 rounded-2xl border border-slate-200 p-4 dark:border-white/10"><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Full customer address</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{reviewing.shipment.locality||'Full address unavailable'}</p><div className="mt-3 flex gap-4 text-xs"><span><b>Pincode:</b> {reviewing.shipment.pincode||'—'}</span><span><b>Suggested:</b> {executives.find(e=>e.id===reviewing.executiveId)?.name||'—'}</span></div></div><label className="mt-4 block"><span className="mb-1.5 block text-xs font-black">Confirm or change employee</span><select className="input-base" value={reviewEmployee} onChange={e=>setReviewEmployee(e.target.value)}><option value="">Select employee</option>{executives.filter(e=>e.active).map(e=><option value={e.id} key={e.id}>{e.name} · {e.employeeId}</option>)}</select></label><div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button onClick={()=>{onReview(reviewing.shipment.awb,null,'reject');closeReview();}} className="rounded-xl border border-red-200 px-4 py-3 text-sm font-black text-red-600">Reject → Send to ODA</button><button disabled={!reviewEmployee} onClick={()=>{onReview(reviewing.shipment.awb,reviewEmployee,'confirm');closeReview();}} className="rounded-xl bg-brand-600 px-5 py-3 text-sm font-black text-white disabled:opacity-40">Confirm Assignment</button></div></div></div>}
  </section>;
}
