import { useToast } from '@/components/ui/Toast';
import { useHub } from '@/lib/hubContext';
import { loadODAShipments, markODAAssigned, ODAShipment } from '@/lib/routeLoad/oda';
import { supabase } from '@/lib/supabase';
import { AlertTriangle, CheckCircle2, Loader2, MapPin, PackageX, Search, UserCheck } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

interface EmployeeOption { id:string; name:string; employeeId:string; deliveryAreas:string[]; deliveryArea:string }

export default function ODAShipments(){
  const {selectedHubId}=useHub();const toast=useToast();
  const [rows,setRows]=useState<ODAShipment[]>([]);const [updatedAt,setUpdatedAt]=useState('');const [search,setSearch]=useState('');const [pincode,setPincode]=useState('all');
  const [employees,setEmployees]=useState<EmployeeOption[]>([]);const [employeeByAwb,setEmployeeByAwb]=useState<Record<string,string>>({});const [areaByAwb,setAreaByAwb]=useState<Record<string,string>>({});const [savingAwb,setSavingAwb]=useState('');
  useEffect(()=>{const refresh=()=>{const data=loadODAShipments(selectedHubId??'');setRows(data.shipments);setUpdatedAt(data.updatedAt);setAreaByAwb(current=>Object.fromEntries(data.shipments.map(row=>[row.awb,current[row.awb]??row.suggestedArea??''])));};refresh();window.addEventListener('hubvault:oda-updated',refresh);return()=>window.removeEventListener('hubvault:oda-updated',refresh);},[selectedHubId]);
  useEffect(()=>{if(!selectedHubId){setEmployees([]);return;}void(async()=>{const {data,error}=await supabase.from('collectors').select('id,name,employee_id,delivery_area,delivery_areas').eq('hub_id',selectedHubId).eq('status','active').order('name');if(error){toast.error(error.message);return;}let availableIds:string[]=[];try{availableIds=JSON.parse(localStorage.getItem(`route-load-available:${selectedHubId}`)??'[]') as string[];}catch{availableIds=[];}const available=new Set(availableIds);setEmployees((data??[]).filter(item=>available.has(item.id)).map(item=>({id:item.id,name:item.name,employeeId:item.employee_id,deliveryAreas:item.delivery_areas??[],deliveryArea:item.delivery_area??''})));})();},[selectedHubId,toast]);
  const pincodes=useMemo(()=>[...new Set(rows.map(row=>row.pincode).filter(Boolean))].sort(),[rows]);
  const visible=useMemo(()=>rows.filter(row=>(pincode==='all'||row.pincode===pincode)&&`${row.awb} ${row.customerName} ${row.pincode} ${row.fullAddress} ${row.assignedEmployeeName??''}`.toLowerCase().includes(search.toLowerCase())),[rows,pincode,search]);
  const assign=async(row:ODAShipment)=>{if(!selectedHubId)return;const employee=employees.find(item=>item.id===employeeByAwb[row.awb]);const area=(areaByAwb[row.awb]??'').trim();if(!employee){toast.error('Select an available employee.');return;}if(area.length<3){toast.error('Confirm a valid area name before assigning.');return;}setSavingAwb(row.awb);try{const existing=[...employee.deliveryAreas,employee.deliveryArea].map(value=>value.trim()).filter(Boolean);const areas=Array.from(new Map([...existing,area].map(value=>[value.toLowerCase(),value])).values());const {error}=await supabase.from('collectors').update({delivery_areas:areas,delivery_area:employee.deliveryArea||area}).eq('id',employee.id).eq('hub_id',selectedHubId);if(error)throw error;markODAAssigned(selectedHubId,row.awb,{id:employee.id,name:employee.name},area);setEmployees(current=>current.map(item=>item.id===employee.id?{...item,deliveryAreas:areas,deliveryArea:item.deliveryArea||area}:item));window.dispatchEvent(new CustomEvent('hubvault:employee-coverage-updated',{detail:{hubId:selectedHubId}}));toast.success(`${row.awb} assigned to ${employee.name}; ${area} added to employee coverage.`);}catch(error){toast.error(error instanceof Error?error.message:'ODA shipment could not be assigned.');}finally{setSavingAwb('');}};
  return <section className="overflow-hidden rounded-[28px] border border-neutral-200 bg-white shadow-sm dark:border-neutral-800 dark:bg-neutral-900">
    <header className="border-b border-neutral-200 bg-gradient-to-r from-amber-50 to-red-50 p-5 dark:border-neutral-800 dark:from-amber-950/30 dark:to-red-950/20 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="rounded-2xl bg-amber-500 p-3 text-white"><PackageX className="h-6 w-6"/></span><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-amber-700 dark:text-amber-300">Out of Delivery Area</p><h2 className="text-2xl font-black text-neutral-950 dark:text-white">ODA Shipments</h2><p className="mt-1 text-xs text-neutral-600 dark:text-neutral-300">Assign an ODA shipment and teach that area to the selected employee for future automatic matching.</p></div></div><div className="rounded-2xl border border-amber-200 bg-white px-5 py-3 text-center dark:border-amber-800 dark:bg-neutral-900"><strong className="block text-2xl text-amber-700 dark:text-amber-300">{rows.filter(row=>!row.assignedEmployeeId).length}</strong><span className="text-[10px] font-black uppercase tracking-wider text-neutral-500">Pending ODA</span></div></div></header>
    <div className="p-4 sm:p-6"><div className="grid gap-3 sm:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400"/><input className="input-base pl-9" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search AWB, customer, pincode or address"/></label><select className="input-base" value={pincode} onChange={event=>setPincode(event.target.value)}><option value="all">All pincodes</option>{pincodes.map(pin=><option key={pin}>{pin}</option>)}</select></div>{updatedAt&&<p className="mt-3 text-[11px] text-neutral-500">Last distribution: {new Date(updatedAt).toLocaleString('en-IN')} · Only today's selected available employees can be assigned.</p>}
    {rows.length===0?<Empty/>:<div className="mt-5 space-y-4">{visible.map(row=><article className={`rounded-2xl border p-4 ${row.assignedEmployeeId?'border-emerald-200 bg-emerald-50/50 dark:border-emerald-800 dark:bg-emerald-950/10':'border-neutral-200 dark:border-neutral-800'}`} key={row.awb}><div className="grid gap-4 xl:grid-cols-[160px_190px_120px_1fr]"><div><p className="text-[10px] font-black uppercase tracking-wider text-neutral-400">AWB</p><p className="mt-1 break-all font-mono text-xs font-black">{row.awb}</p></div><div><p className="text-[10px] font-black uppercase tracking-wider text-neutral-400">Customer</p><p className="mt-1 font-black">{row.customerName||'Unknown customer'}</p></div><div><p className="text-[10px] font-black uppercase tracking-wider text-neutral-400">Pincode</p><p className="mt-1 font-black text-amber-700">{row.pincode||'—'}</p></div><div><p className="text-[10px] font-black uppercase tracking-wider text-neutral-400">Full address</p><p className="mt-1 flex gap-2 text-xs leading-5 text-neutral-600 dark:text-neutral-300"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-amber-500"/>{row.fullAddress||row.destinationCity||'Address unavailable'}</p></div></div>{row.assignedEmployeeId?<div className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-100 p-3 text-xs font-black text-emerald-800 dark:bg-emerald-500/10 dark:text-emerald-300"><CheckCircle2 className="h-4 w-4"/>Assigned to {row.assignedEmployeeName} · Learned area: {row.suggestedArea}</div>:<div className="mt-4 grid gap-3 rounded-2xl bg-neutral-50 p-3 dark:bg-neutral-800/60 lg:grid-cols-[1fr_1fr_auto]"><label><span className="mb-1 block text-[10px] font-black uppercase tracking-wider text-neutral-500">Area to learn</span><input className="input-base" value={areaByAwb[row.awb]??''} onChange={event=>setAreaByAwb(current=>({...current,[row.awb]:event.target.value}))} placeholder="Confirm detected locality"/></label><label><span className="mb-1 block text-[10px] font-black uppercase tracking-wider text-neutral-500">Assign employee</span><select className="input-base" value={employeeByAwb[row.awb]??''} onChange={event=>setEmployeeByAwb(current=>({...current,[row.awb]:event.target.value}))}><option value="">Select available employee</option>{employees.map(employee=><option value={employee.id} key={employee.id}>{employee.name} · {employee.employeeId}</option>)}</select></label><button onClick={()=>void assign(row)} disabled={savingAwb===row.awb||!employees.length} className="inline-flex min-h-11 items-center justify-center gap-2 self-end rounded-xl bg-brand-600 px-5 text-xs font-black text-white disabled:opacity-50">{savingAwb===row.awb?<Loader2 className="h-4 w-4 animate-spin"/>:<UserCheck className="h-4 w-4"/>}Assign & Learn Area</button></div>}</article>)}</div>}</div>
  </section>;
}

function Empty(){return <div className="mt-6 rounded-3xl border border-dashed border-neutral-300 p-10 text-center dark:border-neutral-700"><AlertTriangle className="mx-auto h-9 w-9 text-amber-500"/><h3 className="mt-3 font-black">No ODA data available</h3><p className="mt-1 text-sm text-neutral-500">Load Distribution tab mein Excel upload karke distribution run karein.</p></div>}
