import { useToast } from '@/components/ui/Toast';
import { useHub } from '@/lib/hubContext';
import { supabase } from '@/lib/supabase';
import { MapPinned, Pencil, Plus, Save, Trash2, X } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';

interface DeliveryRoute{id:string;code:string;name:string;areas:string[];active:boolean}
const empty={code:'',name:'',areas:''};
export default function RouteMaster(){const {selectedHubId}=useHub();const toast=useToast();const [routes,setRoutes]=useState<DeliveryRoute[]>([]);const [form,setForm]=useState(empty);const [editing,setEditing]=useState('');const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{if(!selectedHubId){setRoutes([]);return;}const {data,error}=await supabase.from('delivery_routes').select('id,code,name,areas,active').eq('hub_id',selectedHubId).order('code');if(error){toast.error(error.message);return;}setRoutes(data??[]);},[selectedHubId,toast]);useEffect(()=>{void load();},[load]);
  const reset=()=>{setForm(empty);setEditing('');};const edit=(route:DeliveryRoute)=>{setEditing(route.id);setForm({code:route.code,name:route.name,areas:route.areas.join(', ')});};
  const save=async()=>{if(!selectedHubId)return;const areas=Array.from(new Map(form.areas.split(',').map(x=>x.trim()).filter(Boolean).map(x=>[x.toLowerCase(),x])).values());if(!form.code.trim()||!form.name.trim()||!areas.length){toast.error('Route code, name and at least one area are required.');return;}setSaving(true);const payload={hub_id:selectedHubId,code:form.code.trim().toUpperCase(),name:form.name.trim(),areas,updated_at:new Date().toISOString()};const result=editing?await supabase.from('delivery_routes').update(payload).eq('id',editing):await supabase.from('delivery_routes').insert(payload);setSaving(false);if(result.error){toast.error(result.error.message);return;}toast.success(editing?'Route updated.':'Route created.');reset();await load();window.dispatchEvent(new CustomEvent('hubvault:routes-updated'));};
  const remove=async(id:string)=>{if(!confirm('Delete this route? Employee coverage already saved will remain unchanged.'))return;const {error}=await supabase.from('delivery_routes').delete().eq('id',id);if(error)toast.error(error.message);else{toast.success('Route deleted.');await load();}};
  return <section className="rounded-[28px] border border-neutral-200 bg-white p-4 shadow-sm dark:border-neutral-800 dark:bg-neutral-900 sm:p-6"><div className="flex items-center gap-3"><span className="rounded-2xl bg-brand-600 p-3 text-white"><MapPinned className="h-6 w-6"/></span><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-brand-600">Coverage configuration</p><h2 className="text-2xl font-black">Route Master</h2><p className="text-xs text-neutral-500">Create a route once and maintain all delivery areas inside it.</p></div></div><div className="mt-6 grid gap-3 rounded-2xl bg-neutral-50 p-4 dark:bg-neutral-800/60 lg:grid-cols-[180px_1fr_2fr_auto]"><label><span className="mb-1 block text-xs font-bold">Route code</span><input className="input-base" value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="BGU-01"/></label><label><span className="mb-1 block text-xs font-bold">Route name</span><input className="input-base" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Singhoul Route"/></label><label><span className="mb-1 block text-xs font-bold">Areas (comma separated)</span><input className="input-base" value={form.areas} onChange={e=>setForm({...form,areas:e.target.value})} placeholder="Singhoul, Singhaul Dih, Mali Tola, Kumhartoli"/></label><div className="flex items-end gap-2"><button onClick={()=>void save()} disabled={saving} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-brand-600 px-4 text-sm font-black text-white">{editing?<Save className="h-4 w-4"/>:<Plus className="h-4 w-4"/>}{editing?'Update':'Create'}</button>{editing&&<button onClick={reset} className="rounded-xl border p-3"><X className="h-4 w-4"/></button>}</div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{routes.map(route=><article key={route.id} className="rounded-2xl border border-neutral-200 p-4 dark:border-neutral-800"><div className="flex justify-between gap-3"><div><span className="rounded-lg bg-brand-50 px-2 py-1 text-xs font-black text-brand-700 dark:bg-brand-500/10 dark:text-brand-300">{route.code}</span><h3 className="mt-2 font-black">{route.name}</h3></div><div className="flex"><button onClick={()=>edit(route)} className="p-2 text-brand-600"><Pencil className="h-4 w-4"/></button><button onClick={()=>void remove(route.id)} className="p-2 text-red-500"><Trash2 className="h-4 w-4"/></button></div></div><div className="mt-3 flex flex-wrap gap-1.5">{route.areas.map(area=><span key={area} className="rounded-full bg-neutral-100 px-2.5 py-1 text-[11px] font-bold dark:bg-neutral-800">{area}</span>)}</div></article>)}{!routes.length&&<p className="col-span-full py-10 text-center text-sm text-neutral-500">No routes created for this hub.</p>}</div></section>;
}
